// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                        = new(Query)
	Host                     *host
	JobPlan                  *jobPlan
	JobPlanLog               *jobPlanLog
	JobPlanScript            *jobPlanScript
	JobScheduledTask         *jobScheduledTask
	JobScript                *jobScript
	SystemDept               *systemDept
	SystemDictDatum          *systemDictDatum
	SystemDictType           *systemDictType
	SystemLoginLog           *systemLoginLog
	SystemMenu               *systemMenu
	SystemOauth2AccessToken  *systemOauth2AccessToken
	SystemOauth2RefreshToken *systemOauth2RefreshToken
	SystemOperateLog         *systemOperateLog
	SystemPost               *systemPost
	SystemRole               *systemRole
	SystemRoleMenu           *systemRoleMenu
	SystemUser               *systemUser
	SystemUserPost           *systemUserPost
	SystemUserRole           *systemUserRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Host = &Q.Host
	JobPlan = &Q.JobPlan
	JobPlanLog = &Q.JobPlanLog
	JobPlanScript = &Q.JobPlanScript
	JobScheduledTask = &Q.JobScheduledTask
	JobScript = &Q.JobScript
	SystemDept = &Q.SystemDept
	SystemDictDatum = &Q.SystemDictDatum
	SystemDictType = &Q.SystemDictType
	SystemLoginLog = &Q.SystemLoginLog
	SystemMenu = &Q.SystemMenu
	SystemOauth2AccessToken = &Q.SystemOauth2AccessToken
	SystemOauth2RefreshToken = &Q.SystemOauth2RefreshToken
	SystemOperateLog = &Q.SystemOperateLog
	SystemPost = &Q.SystemPost
	SystemRole = &Q.SystemRole
	SystemRoleMenu = &Q.SystemRoleMenu
	SystemUser = &Q.SystemUser
	SystemUserPost = &Q.SystemUserPost
	SystemUserRole = &Q.SystemUserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                       db,
		Host:                     newHost(db, opts...),
		JobPlan:                  newJobPlan(db, opts...),
		JobPlanLog:               newJobPlanLog(db, opts...),
		JobPlanScript:            newJobPlanScript(db, opts...),
		JobScheduledTask:         newJobScheduledTask(db, opts...),
		JobScript:                newJobScript(db, opts...),
		SystemDept:               newSystemDept(db, opts...),
		SystemDictDatum:          newSystemDictDatum(db, opts...),
		SystemDictType:           newSystemDictType(db, opts...),
		SystemLoginLog:           newSystemLoginLog(db, opts...),
		SystemMenu:               newSystemMenu(db, opts...),
		SystemOauth2AccessToken:  newSystemOauth2AccessToken(db, opts...),
		SystemOauth2RefreshToken: newSystemOauth2RefreshToken(db, opts...),
		SystemOperateLog:         newSystemOperateLog(db, opts...),
		SystemPost:               newSystemPost(db, opts...),
		SystemRole:               newSystemRole(db, opts...),
		SystemRoleMenu:           newSystemRoleMenu(db, opts...),
		SystemUser:               newSystemUser(db, opts...),
		SystemUserPost:           newSystemUserPost(db, opts...),
		SystemUserRole:           newSystemUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Host                     host
	JobPlan                  jobPlan
	JobPlanLog               jobPlanLog
	JobPlanScript            jobPlanScript
	JobScheduledTask         jobScheduledTask
	JobScript                jobScript
	SystemDept               systemDept
	SystemDictDatum          systemDictDatum
	SystemDictType           systemDictType
	SystemLoginLog           systemLoginLog
	SystemMenu               systemMenu
	SystemOauth2AccessToken  systemOauth2AccessToken
	SystemOauth2RefreshToken systemOauth2RefreshToken
	SystemOperateLog         systemOperateLog
	SystemPost               systemPost
	SystemRole               systemRole
	SystemRoleMenu           systemRoleMenu
	SystemUser               systemUser
	SystemUserPost           systemUserPost
	SystemUserRole           systemUserRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                       db,
		Host:                     q.Host.clone(db),
		JobPlan:                  q.JobPlan.clone(db),
		JobPlanLog:               q.JobPlanLog.clone(db),
		JobPlanScript:            q.JobPlanScript.clone(db),
		JobScheduledTask:         q.JobScheduledTask.clone(db),
		JobScript:                q.JobScript.clone(db),
		SystemDept:               q.SystemDept.clone(db),
		SystemDictDatum:          q.SystemDictDatum.clone(db),
		SystemDictType:           q.SystemDictType.clone(db),
		SystemLoginLog:           q.SystemLoginLog.clone(db),
		SystemMenu:               q.SystemMenu.clone(db),
		SystemOauth2AccessToken:  q.SystemOauth2AccessToken.clone(db),
		SystemOauth2RefreshToken: q.SystemOauth2RefreshToken.clone(db),
		SystemOperateLog:         q.SystemOperateLog.clone(db),
		SystemPost:               q.SystemPost.clone(db),
		SystemRole:               q.SystemRole.clone(db),
		SystemRoleMenu:           q.SystemRoleMenu.clone(db),
		SystemUser:               q.SystemUser.clone(db),
		SystemUserPost:           q.SystemUserPost.clone(db),
		SystemUserRole:           q.SystemUserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                       db,
		Host:                     q.Host.replaceDB(db),
		JobPlan:                  q.JobPlan.replaceDB(db),
		JobPlanLog:               q.JobPlanLog.replaceDB(db),
		JobPlanScript:            q.JobPlanScript.replaceDB(db),
		JobScheduledTask:         q.JobScheduledTask.replaceDB(db),
		JobScript:                q.JobScript.replaceDB(db),
		SystemDept:               q.SystemDept.replaceDB(db),
		SystemDictDatum:          q.SystemDictDatum.replaceDB(db),
		SystemDictType:           q.SystemDictType.replaceDB(db),
		SystemLoginLog:           q.SystemLoginLog.replaceDB(db),
		SystemMenu:               q.SystemMenu.replaceDB(db),
		SystemOauth2AccessToken:  q.SystemOauth2AccessToken.replaceDB(db),
		SystemOauth2RefreshToken: q.SystemOauth2RefreshToken.replaceDB(db),
		SystemOperateLog:         q.SystemOperateLog.replaceDB(db),
		SystemPost:               q.SystemPost.replaceDB(db),
		SystemRole:               q.SystemRole.replaceDB(db),
		SystemRoleMenu:           q.SystemRoleMenu.replaceDB(db),
		SystemUser:               q.SystemUser.replaceDB(db),
		SystemUserPost:           q.SystemUserPost.replaceDB(db),
		SystemUserRole:           q.SystemUserRole.replaceDB(db),
	}
}

type queryCtx struct {
	Host                     IHostDo
	JobPlan                  IJobPlanDo
	JobPlanLog               IJobPlanLogDo
	JobPlanScript            IJobPlanScriptDo
	JobScheduledTask         IJobScheduledTaskDo
	JobScript                IJobScriptDo
	SystemDept               ISystemDeptDo
	SystemDictDatum          ISystemDictDatumDo
	SystemDictType           ISystemDictTypeDo
	SystemLoginLog           ISystemLoginLogDo
	SystemMenu               ISystemMenuDo
	SystemOauth2AccessToken  ISystemOauth2AccessTokenDo
	SystemOauth2RefreshToken ISystemOauth2RefreshTokenDo
	SystemOperateLog         ISystemOperateLogDo
	SystemPost               ISystemPostDo
	SystemRole               ISystemRoleDo
	SystemRoleMenu           ISystemRoleMenuDo
	SystemUser               ISystemUserDo
	SystemUserPost           ISystemUserPostDo
	SystemUserRole           ISystemUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Host:                     q.Host.WithContext(ctx),
		JobPlan:                  q.JobPlan.WithContext(ctx),
		JobPlanLog:               q.JobPlanLog.WithContext(ctx),
		JobPlanScript:            q.JobPlanScript.WithContext(ctx),
		JobScheduledTask:         q.JobScheduledTask.WithContext(ctx),
		JobScript:                q.JobScript.WithContext(ctx),
		SystemDept:               q.SystemDept.WithContext(ctx),
		SystemDictDatum:          q.SystemDictDatum.WithContext(ctx),
		SystemDictType:           q.SystemDictType.WithContext(ctx),
		SystemLoginLog:           q.SystemLoginLog.WithContext(ctx),
		SystemMenu:               q.SystemMenu.WithContext(ctx),
		SystemOauth2AccessToken:  q.SystemOauth2AccessToken.WithContext(ctx),
		SystemOauth2RefreshToken: q.SystemOauth2RefreshToken.WithContext(ctx),
		SystemOperateLog:         q.SystemOperateLog.WithContext(ctx),
		SystemPost:               q.SystemPost.WithContext(ctx),
		SystemRole:               q.SystemRole.WithContext(ctx),
		SystemRoleMenu:           q.SystemRoleMenu.WithContext(ctx),
		SystemUser:               q.SystemUser.WithContext(ctx),
		SystemUserPost:           q.SystemUserPost.WithContext(ctx),
		SystemUserRole:           q.SystemUserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
