// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newJobScheduledTask(db *gorm.DB, opts ...gen.DOOption) jobScheduledTask {
	_jobScheduledTask := jobScheduledTask{}

	_jobScheduledTask.jobScheduledTaskDo.UseDB(db, opts...)
	_jobScheduledTask.jobScheduledTaskDo.UseModel(&model.JobScheduledTask{})

	tableName := _jobScheduledTask.jobScheduledTaskDo.TableName()
	_jobScheduledTask.ALL = field.NewAsterisk(tableName)
	_jobScheduledTask.ID = field.NewUint32(tableName, "id")
	_jobScheduledTask.Name = field.NewString(tableName, "name")
	_jobScheduledTask.PlanID = field.NewUint32(tableName, "plan_id")
	_jobScheduledTask.Strategy = field.NewString(tableName, "strategy")
	_jobScheduledTask.LeatestStatus = field.NewString(tableName, "leatest_status")
	_jobScheduledTask.SycleSuccessRate = field.NewString(tableName, "sycle_success_rate")
	_jobScheduledTask.Status = field.NewUint32(tableName, "status")
	_jobScheduledTask.CreatedAt = field.NewTime(tableName, "created_at")
	_jobScheduledTask.UpdatedAt = field.NewTime(tableName, "updated_at")
	_jobScheduledTask.DeletedAt = field.NewField(tableName, "deleted_at")

	_jobScheduledTask.fillFieldMap()

	return _jobScheduledTask
}

// jobScheduledTask 定时任务
type jobScheduledTask struct {
	jobScheduledTaskDo

	ALL              field.Asterisk
	ID               field.Uint32 // 主键id
	Name             field.String // 任务名称
	PlanID           field.Uint32 // 计划id
	Strategy         field.String // 执行策略
	LeatestStatus    field.String // 最新执行结果
	SycleSuccessRate field.String // 周期成功率
	Status           field.Uint32 // 是否开启
	CreatedAt        field.Time   // 创建时间
	UpdatedAt        field.Time   // 更新时间
	DeletedAt        field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (j jobScheduledTask) Table(newTableName string) *jobScheduledTask {
	j.jobScheduledTaskDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobScheduledTask) As(alias string) *jobScheduledTask {
	j.jobScheduledTaskDo.DO = *(j.jobScheduledTaskDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobScheduledTask) updateTableName(table string) *jobScheduledTask {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewUint32(table, "id")
	j.Name = field.NewString(table, "name")
	j.PlanID = field.NewUint32(table, "plan_id")
	j.Strategy = field.NewString(table, "strategy")
	j.LeatestStatus = field.NewString(table, "leatest_status")
	j.SycleSuccessRate = field.NewString(table, "sycle_success_rate")
	j.Status = field.NewUint32(table, "status")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.DeletedAt = field.NewField(table, "deleted_at")

	j.fillFieldMap()

	return j
}

func (j *jobScheduledTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobScheduledTask) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 10)
	j.fieldMap["id"] = j.ID
	j.fieldMap["name"] = j.Name
	j.fieldMap["plan_id"] = j.PlanID
	j.fieldMap["strategy"] = j.Strategy
	j.fieldMap["leatest_status"] = j.LeatestStatus
	j.fieldMap["sycle_success_rate"] = j.SycleSuccessRate
	j.fieldMap["status"] = j.Status
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["deleted_at"] = j.DeletedAt
}

func (j jobScheduledTask) clone(db *gorm.DB) jobScheduledTask {
	j.jobScheduledTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobScheduledTask) replaceDB(db *gorm.DB) jobScheduledTask {
	j.jobScheduledTaskDo.ReplaceDB(db)
	return j
}

type jobScheduledTaskDo struct{ gen.DO }

type IJobScheduledTaskDo interface {
	gen.SubQuery
	Debug() IJobScheduledTaskDo
	WithContext(ctx context.Context) IJobScheduledTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobScheduledTaskDo
	WriteDB() IJobScheduledTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobScheduledTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobScheduledTaskDo
	Not(conds ...gen.Condition) IJobScheduledTaskDo
	Or(conds ...gen.Condition) IJobScheduledTaskDo
	Select(conds ...field.Expr) IJobScheduledTaskDo
	Where(conds ...gen.Condition) IJobScheduledTaskDo
	Order(conds ...field.Expr) IJobScheduledTaskDo
	Distinct(cols ...field.Expr) IJobScheduledTaskDo
	Omit(cols ...field.Expr) IJobScheduledTaskDo
	Join(table schema.Tabler, on ...field.Expr) IJobScheduledTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobScheduledTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobScheduledTaskDo
	Group(cols ...field.Expr) IJobScheduledTaskDo
	Having(conds ...gen.Condition) IJobScheduledTaskDo
	Limit(limit int) IJobScheduledTaskDo
	Offset(offset int) IJobScheduledTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobScheduledTaskDo
	Unscoped() IJobScheduledTaskDo
	Create(values ...*model.JobScheduledTask) error
	CreateInBatches(values []*model.JobScheduledTask, batchSize int) error
	Save(values ...*model.JobScheduledTask) error
	First() (*model.JobScheduledTask, error)
	Take() (*model.JobScheduledTask, error)
	Last() (*model.JobScheduledTask, error)
	Find() ([]*model.JobScheduledTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobScheduledTask, err error)
	FindInBatches(result *[]*model.JobScheduledTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.JobScheduledTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobScheduledTaskDo
	Assign(attrs ...field.AssignExpr) IJobScheduledTaskDo
	Joins(fields ...field.RelationField) IJobScheduledTaskDo
	Preload(fields ...field.RelationField) IJobScheduledTaskDo
	FirstOrInit() (*model.JobScheduledTask, error)
	FirstOrCreate() (*model.JobScheduledTask, error)
	FindByPage(offset int, limit int) (result []*model.JobScheduledTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobScheduledTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobScheduledTaskDo) Debug() IJobScheduledTaskDo {
	return j.withDO(j.DO.Debug())
}

func (j jobScheduledTaskDo) WithContext(ctx context.Context) IJobScheduledTaskDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobScheduledTaskDo) ReadDB() IJobScheduledTaskDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobScheduledTaskDo) WriteDB() IJobScheduledTaskDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobScheduledTaskDo) Session(config *gorm.Session) IJobScheduledTaskDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobScheduledTaskDo) Clauses(conds ...clause.Expression) IJobScheduledTaskDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobScheduledTaskDo) Returning(value interface{}, columns ...string) IJobScheduledTaskDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobScheduledTaskDo) Not(conds ...gen.Condition) IJobScheduledTaskDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobScheduledTaskDo) Or(conds ...gen.Condition) IJobScheduledTaskDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobScheduledTaskDo) Select(conds ...field.Expr) IJobScheduledTaskDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobScheduledTaskDo) Where(conds ...gen.Condition) IJobScheduledTaskDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobScheduledTaskDo) Order(conds ...field.Expr) IJobScheduledTaskDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobScheduledTaskDo) Distinct(cols ...field.Expr) IJobScheduledTaskDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobScheduledTaskDo) Omit(cols ...field.Expr) IJobScheduledTaskDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobScheduledTaskDo) Join(table schema.Tabler, on ...field.Expr) IJobScheduledTaskDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobScheduledTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobScheduledTaskDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobScheduledTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobScheduledTaskDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobScheduledTaskDo) Group(cols ...field.Expr) IJobScheduledTaskDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobScheduledTaskDo) Having(conds ...gen.Condition) IJobScheduledTaskDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobScheduledTaskDo) Limit(limit int) IJobScheduledTaskDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobScheduledTaskDo) Offset(offset int) IJobScheduledTaskDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobScheduledTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobScheduledTaskDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobScheduledTaskDo) Unscoped() IJobScheduledTaskDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobScheduledTaskDo) Create(values ...*model.JobScheduledTask) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobScheduledTaskDo) CreateInBatches(values []*model.JobScheduledTask, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobScheduledTaskDo) Save(values ...*model.JobScheduledTask) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobScheduledTaskDo) First() (*model.JobScheduledTask, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScheduledTask), nil
	}
}

func (j jobScheduledTaskDo) Take() (*model.JobScheduledTask, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScheduledTask), nil
	}
}

func (j jobScheduledTaskDo) Last() (*model.JobScheduledTask, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScheduledTask), nil
	}
}

func (j jobScheduledTaskDo) Find() ([]*model.JobScheduledTask, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobScheduledTask), err
}

func (j jobScheduledTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobScheduledTask, err error) {
	buf := make([]*model.JobScheduledTask, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobScheduledTaskDo) FindInBatches(result *[]*model.JobScheduledTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobScheduledTaskDo) Attrs(attrs ...field.AssignExpr) IJobScheduledTaskDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobScheduledTaskDo) Assign(attrs ...field.AssignExpr) IJobScheduledTaskDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobScheduledTaskDo) Joins(fields ...field.RelationField) IJobScheduledTaskDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobScheduledTaskDo) Preload(fields ...field.RelationField) IJobScheduledTaskDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobScheduledTaskDo) FirstOrInit() (*model.JobScheduledTask, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScheduledTask), nil
	}
}

func (j jobScheduledTaskDo) FirstOrCreate() (*model.JobScheduledTask, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScheduledTask), nil
	}
}

func (j jobScheduledTaskDo) FindByPage(offset int, limit int) (result []*model.JobScheduledTask, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobScheduledTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobScheduledTaskDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobScheduledTaskDo) Delete(models ...*model.JobScheduledTask) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobScheduledTaskDo) withDO(do gen.Dao) *jobScheduledTaskDo {
	j.DO = *do.(*gen.DO)
	return j
}
