// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newJobPlanScript(db *gorm.DB, opts ...gen.DOOption) jobPlanScript {
	_jobPlanScript := jobPlanScript{}

	_jobPlanScript.jobPlanScriptDo.UseDB(db, opts...)
	_jobPlanScript.jobPlanScriptDo.UseModel(&model.JobPlanScript{})

	tableName := _jobPlanScript.jobPlanScriptDo.TableName()
	_jobPlanScript.ALL = field.NewAsterisk(tableName)
	_jobPlanScript.ID = field.NewUint32(tableName, "id")
	_jobPlanScript.PlanID = field.NewInt32(tableName, "plan_id")
	_jobPlanScript.ScriptID = field.NewInt32(tableName, "script_id")
	_jobPlanScript.Sort = field.NewUint32(tableName, "sort")
	_jobPlanScript.CreatedAt = field.NewTime(tableName, "created_at")
	_jobPlanScript.UpdatedAt = field.NewTime(tableName, "updated_at")
	_jobPlanScript.DeletedAt = field.NewField(tableName, "deleted_at")

	_jobPlanScript.fillFieldMap()

	return _jobPlanScript
}

type jobPlanScript struct {
	jobPlanScriptDo

	ALL       field.Asterisk
	ID        field.Uint32 // 主键id
	PlanID    field.Int32  // 计划id
	ScriptID  field.Int32  // 脚本id
	Sort      field.Uint32 // 排序
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (j jobPlanScript) Table(newTableName string) *jobPlanScript {
	j.jobPlanScriptDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobPlanScript) As(alias string) *jobPlanScript {
	j.jobPlanScriptDo.DO = *(j.jobPlanScriptDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobPlanScript) updateTableName(table string) *jobPlanScript {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewUint32(table, "id")
	j.PlanID = field.NewInt32(table, "plan_id")
	j.ScriptID = field.NewInt32(table, "script_id")
	j.Sort = field.NewUint32(table, "sort")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.DeletedAt = field.NewField(table, "deleted_at")

	j.fillFieldMap()

	return j
}

func (j *jobPlanScript) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobPlanScript) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 7)
	j.fieldMap["id"] = j.ID
	j.fieldMap["plan_id"] = j.PlanID
	j.fieldMap["script_id"] = j.ScriptID
	j.fieldMap["sort"] = j.Sort
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["deleted_at"] = j.DeletedAt
}

func (j jobPlanScript) clone(db *gorm.DB) jobPlanScript {
	j.jobPlanScriptDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobPlanScript) replaceDB(db *gorm.DB) jobPlanScript {
	j.jobPlanScriptDo.ReplaceDB(db)
	return j
}

type jobPlanScriptDo struct{ gen.DO }

type IJobPlanScriptDo interface {
	gen.SubQuery
	Debug() IJobPlanScriptDo
	WithContext(ctx context.Context) IJobPlanScriptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobPlanScriptDo
	WriteDB() IJobPlanScriptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobPlanScriptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobPlanScriptDo
	Not(conds ...gen.Condition) IJobPlanScriptDo
	Or(conds ...gen.Condition) IJobPlanScriptDo
	Select(conds ...field.Expr) IJobPlanScriptDo
	Where(conds ...gen.Condition) IJobPlanScriptDo
	Order(conds ...field.Expr) IJobPlanScriptDo
	Distinct(cols ...field.Expr) IJobPlanScriptDo
	Omit(cols ...field.Expr) IJobPlanScriptDo
	Join(table schema.Tabler, on ...field.Expr) IJobPlanScriptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobPlanScriptDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobPlanScriptDo
	Group(cols ...field.Expr) IJobPlanScriptDo
	Having(conds ...gen.Condition) IJobPlanScriptDo
	Limit(limit int) IJobPlanScriptDo
	Offset(offset int) IJobPlanScriptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobPlanScriptDo
	Unscoped() IJobPlanScriptDo
	Create(values ...*model.JobPlanScript) error
	CreateInBatches(values []*model.JobPlanScript, batchSize int) error
	Save(values ...*model.JobPlanScript) error
	First() (*model.JobPlanScript, error)
	Take() (*model.JobPlanScript, error)
	Last() (*model.JobPlanScript, error)
	Find() ([]*model.JobPlanScript, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobPlanScript, err error)
	FindInBatches(result *[]*model.JobPlanScript, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.JobPlanScript) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobPlanScriptDo
	Assign(attrs ...field.AssignExpr) IJobPlanScriptDo
	Joins(fields ...field.RelationField) IJobPlanScriptDo
	Preload(fields ...field.RelationField) IJobPlanScriptDo
	FirstOrInit() (*model.JobPlanScript, error)
	FirstOrCreate() (*model.JobPlanScript, error)
	FindByPage(offset int, limit int) (result []*model.JobPlanScript, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobPlanScriptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobPlanScriptDo) Debug() IJobPlanScriptDo {
	return j.withDO(j.DO.Debug())
}

func (j jobPlanScriptDo) WithContext(ctx context.Context) IJobPlanScriptDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobPlanScriptDo) ReadDB() IJobPlanScriptDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobPlanScriptDo) WriteDB() IJobPlanScriptDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobPlanScriptDo) Session(config *gorm.Session) IJobPlanScriptDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobPlanScriptDo) Clauses(conds ...clause.Expression) IJobPlanScriptDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobPlanScriptDo) Returning(value interface{}, columns ...string) IJobPlanScriptDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobPlanScriptDo) Not(conds ...gen.Condition) IJobPlanScriptDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobPlanScriptDo) Or(conds ...gen.Condition) IJobPlanScriptDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobPlanScriptDo) Select(conds ...field.Expr) IJobPlanScriptDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobPlanScriptDo) Where(conds ...gen.Condition) IJobPlanScriptDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobPlanScriptDo) Order(conds ...field.Expr) IJobPlanScriptDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobPlanScriptDo) Distinct(cols ...field.Expr) IJobPlanScriptDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobPlanScriptDo) Omit(cols ...field.Expr) IJobPlanScriptDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobPlanScriptDo) Join(table schema.Tabler, on ...field.Expr) IJobPlanScriptDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobPlanScriptDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobPlanScriptDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobPlanScriptDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobPlanScriptDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobPlanScriptDo) Group(cols ...field.Expr) IJobPlanScriptDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobPlanScriptDo) Having(conds ...gen.Condition) IJobPlanScriptDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobPlanScriptDo) Limit(limit int) IJobPlanScriptDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobPlanScriptDo) Offset(offset int) IJobPlanScriptDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobPlanScriptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobPlanScriptDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobPlanScriptDo) Unscoped() IJobPlanScriptDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobPlanScriptDo) Create(values ...*model.JobPlanScript) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobPlanScriptDo) CreateInBatches(values []*model.JobPlanScript, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobPlanScriptDo) Save(values ...*model.JobPlanScript) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobPlanScriptDo) First() (*model.JobPlanScript, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanScript), nil
	}
}

func (j jobPlanScriptDo) Take() (*model.JobPlanScript, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanScript), nil
	}
}

func (j jobPlanScriptDo) Last() (*model.JobPlanScript, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanScript), nil
	}
}

func (j jobPlanScriptDo) Find() ([]*model.JobPlanScript, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobPlanScript), err
}

func (j jobPlanScriptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobPlanScript, err error) {
	buf := make([]*model.JobPlanScript, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobPlanScriptDo) FindInBatches(result *[]*model.JobPlanScript, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobPlanScriptDo) Attrs(attrs ...field.AssignExpr) IJobPlanScriptDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobPlanScriptDo) Assign(attrs ...field.AssignExpr) IJobPlanScriptDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobPlanScriptDo) Joins(fields ...field.RelationField) IJobPlanScriptDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobPlanScriptDo) Preload(fields ...field.RelationField) IJobPlanScriptDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobPlanScriptDo) FirstOrInit() (*model.JobPlanScript, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanScript), nil
	}
}

func (j jobPlanScriptDo) FirstOrCreate() (*model.JobPlanScript, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanScript), nil
	}
}

func (j jobPlanScriptDo) FindByPage(offset int, limit int) (result []*model.JobPlanScript, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobPlanScriptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobPlanScriptDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobPlanScriptDo) Delete(models ...*model.JobPlanScript) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobPlanScriptDo) withDO(do gen.Dao) *jobPlanScriptDo {
	j.DO = *do.(*gen.DO)
	return j
}
