// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newJobPlan(db *gorm.DB, opts ...gen.DOOption) jobPlan {
	_jobPlan := jobPlan{}

	_jobPlan.jobPlanDo.UseDB(db, opts...)
	_jobPlan.jobPlanDo.UseModel(&model.JobPlan{})

	tableName := _jobPlan.jobPlanDo.TableName()
	_jobPlan.ALL = field.NewAsterisk(tableName)
	_jobPlan.ID = field.NewUint32(tableName, "id")
	_jobPlan.Name = field.NewString(tableName, "name")
	_jobPlan.GlobalVars = field.NewString(tableName, "global_vars")
	_jobPlan.HostIds = field.NewString(tableName, "host_ids")
	_jobPlan.HostGroupID = field.NewUint32(tableName, "host_group_id")
	_jobPlan.Remark = field.NewString(tableName, "remark")
	_jobPlan.CreatedAt = field.NewTime(tableName, "created_at")
	_jobPlan.UpdatedAt = field.NewTime(tableName, "updated_at")
	_jobPlan.DeletedAt = field.NewField(tableName, "deleted_at")

	_jobPlan.fillFieldMap()

	return _jobPlan
}

// jobPlan 执行计划
type jobPlan struct {
	jobPlanDo

	ALL         field.Asterisk
	ID          field.Uint32 // 主键id
	Name        field.String // 任务名称
	GlobalVars  field.String // 全局变量
	HostIds     field.String // 主机列表
	HostGroupID field.Uint32 // 主机组id
	Remark      field.String // 备注
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	DeletedAt   field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (j jobPlan) Table(newTableName string) *jobPlan {
	j.jobPlanDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobPlan) As(alias string) *jobPlan {
	j.jobPlanDo.DO = *(j.jobPlanDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobPlan) updateTableName(table string) *jobPlan {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewUint32(table, "id")
	j.Name = field.NewString(table, "name")
	j.GlobalVars = field.NewString(table, "global_vars")
	j.HostIds = field.NewString(table, "host_ids")
	j.HostGroupID = field.NewUint32(table, "host_group_id")
	j.Remark = field.NewString(table, "remark")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.DeletedAt = field.NewField(table, "deleted_at")

	j.fillFieldMap()

	return j
}

func (j *jobPlan) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobPlan) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 9)
	j.fieldMap["id"] = j.ID
	j.fieldMap["name"] = j.Name
	j.fieldMap["global_vars"] = j.GlobalVars
	j.fieldMap["host_ids"] = j.HostIds
	j.fieldMap["host_group_id"] = j.HostGroupID
	j.fieldMap["remark"] = j.Remark
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["deleted_at"] = j.DeletedAt
}

func (j jobPlan) clone(db *gorm.DB) jobPlan {
	j.jobPlanDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobPlan) replaceDB(db *gorm.DB) jobPlan {
	j.jobPlanDo.ReplaceDB(db)
	return j
}

type jobPlanDo struct{ gen.DO }

type IJobPlanDo interface {
	gen.SubQuery
	Debug() IJobPlanDo
	WithContext(ctx context.Context) IJobPlanDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobPlanDo
	WriteDB() IJobPlanDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobPlanDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobPlanDo
	Not(conds ...gen.Condition) IJobPlanDo
	Or(conds ...gen.Condition) IJobPlanDo
	Select(conds ...field.Expr) IJobPlanDo
	Where(conds ...gen.Condition) IJobPlanDo
	Order(conds ...field.Expr) IJobPlanDo
	Distinct(cols ...field.Expr) IJobPlanDo
	Omit(cols ...field.Expr) IJobPlanDo
	Join(table schema.Tabler, on ...field.Expr) IJobPlanDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobPlanDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobPlanDo
	Group(cols ...field.Expr) IJobPlanDo
	Having(conds ...gen.Condition) IJobPlanDo
	Limit(limit int) IJobPlanDo
	Offset(offset int) IJobPlanDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobPlanDo
	Unscoped() IJobPlanDo
	Create(values ...*model.JobPlan) error
	CreateInBatches(values []*model.JobPlan, batchSize int) error
	Save(values ...*model.JobPlan) error
	First() (*model.JobPlan, error)
	Take() (*model.JobPlan, error)
	Last() (*model.JobPlan, error)
	Find() ([]*model.JobPlan, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobPlan, err error)
	FindInBatches(result *[]*model.JobPlan, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.JobPlan) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobPlanDo
	Assign(attrs ...field.AssignExpr) IJobPlanDo
	Joins(fields ...field.RelationField) IJobPlanDo
	Preload(fields ...field.RelationField) IJobPlanDo
	FirstOrInit() (*model.JobPlan, error)
	FirstOrCreate() (*model.JobPlan, error)
	FindByPage(offset int, limit int) (result []*model.JobPlan, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobPlanDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobPlanDo) Debug() IJobPlanDo {
	return j.withDO(j.DO.Debug())
}

func (j jobPlanDo) WithContext(ctx context.Context) IJobPlanDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobPlanDo) ReadDB() IJobPlanDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobPlanDo) WriteDB() IJobPlanDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobPlanDo) Session(config *gorm.Session) IJobPlanDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobPlanDo) Clauses(conds ...clause.Expression) IJobPlanDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobPlanDo) Returning(value interface{}, columns ...string) IJobPlanDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobPlanDo) Not(conds ...gen.Condition) IJobPlanDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobPlanDo) Or(conds ...gen.Condition) IJobPlanDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobPlanDo) Select(conds ...field.Expr) IJobPlanDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobPlanDo) Where(conds ...gen.Condition) IJobPlanDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobPlanDo) Order(conds ...field.Expr) IJobPlanDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobPlanDo) Distinct(cols ...field.Expr) IJobPlanDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobPlanDo) Omit(cols ...field.Expr) IJobPlanDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobPlanDo) Join(table schema.Tabler, on ...field.Expr) IJobPlanDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobPlanDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobPlanDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobPlanDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobPlanDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobPlanDo) Group(cols ...field.Expr) IJobPlanDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobPlanDo) Having(conds ...gen.Condition) IJobPlanDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobPlanDo) Limit(limit int) IJobPlanDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobPlanDo) Offset(offset int) IJobPlanDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobPlanDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobPlanDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobPlanDo) Unscoped() IJobPlanDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobPlanDo) Create(values ...*model.JobPlan) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobPlanDo) CreateInBatches(values []*model.JobPlan, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobPlanDo) Save(values ...*model.JobPlan) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobPlanDo) First() (*model.JobPlan, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlan), nil
	}
}

func (j jobPlanDo) Take() (*model.JobPlan, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlan), nil
	}
}

func (j jobPlanDo) Last() (*model.JobPlan, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlan), nil
	}
}

func (j jobPlanDo) Find() ([]*model.JobPlan, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobPlan), err
}

func (j jobPlanDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobPlan, err error) {
	buf := make([]*model.JobPlan, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobPlanDo) FindInBatches(result *[]*model.JobPlan, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobPlanDo) Attrs(attrs ...field.AssignExpr) IJobPlanDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobPlanDo) Assign(attrs ...field.AssignExpr) IJobPlanDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobPlanDo) Joins(fields ...field.RelationField) IJobPlanDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobPlanDo) Preload(fields ...field.RelationField) IJobPlanDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobPlanDo) FirstOrInit() (*model.JobPlan, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlan), nil
	}
}

func (j jobPlanDo) FirstOrCreate() (*model.JobPlan, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlan), nil
	}
}

func (j jobPlanDo) FindByPage(offset int, limit int) (result []*model.JobPlan, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobPlanDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobPlanDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobPlanDo) Delete(models ...*model.JobPlan) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobPlanDo) withDO(do gen.Dao) *jobPlanDo {
	j.DO = *do.(*gen.DO)
	return j
}
