// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newJobPlanLog(db *gorm.DB, opts ...gen.DOOption) jobPlanLog {
	_jobPlanLog := jobPlanLog{}

	_jobPlanLog.jobPlanLogDo.UseDB(db, opts...)
	_jobPlanLog.jobPlanLogDo.UseModel(&model.JobPlanLog{})

	tableName := _jobPlanLog.jobPlanLogDo.TableName()
	_jobPlanLog.ALL = field.NewAsterisk(tableName)
	_jobPlanLog.ID = field.NewInt32(tableName, "id")
	_jobPlanLog.PlanID = field.NewInt32(tableName, "plan_id")
	_jobPlanLog.HostID = field.NewUint32(tableName, "host_id")
	_jobPlanLog.Method = field.NewString(tableName, "method")
	_jobPlanLog.Type = field.NewString(tableName, "type")
	_jobPlanLog.Status = field.NewBool(tableName, "status")
	_jobPlanLog.TotalTime = field.NewString(tableName, "total_time")
	_jobPlanLog.ReturnCode = field.NewInt32(tableName, "return_code")
	_jobPlanLog.Output = field.NewString(tableName, "output")
	_jobPlanLog.CreatedAt = field.NewTime(tableName, "created_at")
	_jobPlanLog.UpdatedAt = field.NewTime(tableName, "updated_at")
	_jobPlanLog.DeletedAt = field.NewField(tableName, "deleted_at")

	_jobPlanLog.fillFieldMap()

	return _jobPlanLog
}

type jobPlanLog struct {
	jobPlanLogDo

	ALL        field.Asterisk
	ID         field.Int32  // 主键id
	PlanID     field.Int32  // 计划id
	HostID     field.Uint32 // 主机id
	Method     field.String // 执行方式
	Type       field.String // 任务类型
	Status     field.Bool   // 执行状态
	TotalTime  field.String // 总耗时
	ReturnCode field.Int32  // 退出码
	Output     field.String // 日志
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	DeletedAt  field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (j jobPlanLog) Table(newTableName string) *jobPlanLog {
	j.jobPlanLogDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobPlanLog) As(alias string) *jobPlanLog {
	j.jobPlanLogDo.DO = *(j.jobPlanLogDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobPlanLog) updateTableName(table string) *jobPlanLog {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt32(table, "id")
	j.PlanID = field.NewInt32(table, "plan_id")
	j.HostID = field.NewUint32(table, "host_id")
	j.Method = field.NewString(table, "method")
	j.Type = field.NewString(table, "type")
	j.Status = field.NewBool(table, "status")
	j.TotalTime = field.NewString(table, "total_time")
	j.ReturnCode = field.NewInt32(table, "return_code")
	j.Output = field.NewString(table, "output")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.DeletedAt = field.NewField(table, "deleted_at")

	j.fillFieldMap()

	return j
}

func (j *jobPlanLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobPlanLog) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 12)
	j.fieldMap["id"] = j.ID
	j.fieldMap["plan_id"] = j.PlanID
	j.fieldMap["host_id"] = j.HostID
	j.fieldMap["method"] = j.Method
	j.fieldMap["type"] = j.Type
	j.fieldMap["status"] = j.Status
	j.fieldMap["total_time"] = j.TotalTime
	j.fieldMap["return_code"] = j.ReturnCode
	j.fieldMap["output"] = j.Output
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["deleted_at"] = j.DeletedAt
}

func (j jobPlanLog) clone(db *gorm.DB) jobPlanLog {
	j.jobPlanLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobPlanLog) replaceDB(db *gorm.DB) jobPlanLog {
	j.jobPlanLogDo.ReplaceDB(db)
	return j
}

type jobPlanLogDo struct{ gen.DO }

type IJobPlanLogDo interface {
	gen.SubQuery
	Debug() IJobPlanLogDo
	WithContext(ctx context.Context) IJobPlanLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobPlanLogDo
	WriteDB() IJobPlanLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobPlanLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobPlanLogDo
	Not(conds ...gen.Condition) IJobPlanLogDo
	Or(conds ...gen.Condition) IJobPlanLogDo
	Select(conds ...field.Expr) IJobPlanLogDo
	Where(conds ...gen.Condition) IJobPlanLogDo
	Order(conds ...field.Expr) IJobPlanLogDo
	Distinct(cols ...field.Expr) IJobPlanLogDo
	Omit(cols ...field.Expr) IJobPlanLogDo
	Join(table schema.Tabler, on ...field.Expr) IJobPlanLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobPlanLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobPlanLogDo
	Group(cols ...field.Expr) IJobPlanLogDo
	Having(conds ...gen.Condition) IJobPlanLogDo
	Limit(limit int) IJobPlanLogDo
	Offset(offset int) IJobPlanLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobPlanLogDo
	Unscoped() IJobPlanLogDo
	Create(values ...*model.JobPlanLog) error
	CreateInBatches(values []*model.JobPlanLog, batchSize int) error
	Save(values ...*model.JobPlanLog) error
	First() (*model.JobPlanLog, error)
	Take() (*model.JobPlanLog, error)
	Last() (*model.JobPlanLog, error)
	Find() ([]*model.JobPlanLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobPlanLog, err error)
	FindInBatches(result *[]*model.JobPlanLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.JobPlanLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobPlanLogDo
	Assign(attrs ...field.AssignExpr) IJobPlanLogDo
	Joins(fields ...field.RelationField) IJobPlanLogDo
	Preload(fields ...field.RelationField) IJobPlanLogDo
	FirstOrInit() (*model.JobPlanLog, error)
	FirstOrCreate() (*model.JobPlanLog, error)
	FindByPage(offset int, limit int) (result []*model.JobPlanLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobPlanLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobPlanLogDo) Debug() IJobPlanLogDo {
	return j.withDO(j.DO.Debug())
}

func (j jobPlanLogDo) WithContext(ctx context.Context) IJobPlanLogDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobPlanLogDo) ReadDB() IJobPlanLogDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobPlanLogDo) WriteDB() IJobPlanLogDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobPlanLogDo) Session(config *gorm.Session) IJobPlanLogDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobPlanLogDo) Clauses(conds ...clause.Expression) IJobPlanLogDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobPlanLogDo) Returning(value interface{}, columns ...string) IJobPlanLogDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobPlanLogDo) Not(conds ...gen.Condition) IJobPlanLogDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobPlanLogDo) Or(conds ...gen.Condition) IJobPlanLogDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobPlanLogDo) Select(conds ...field.Expr) IJobPlanLogDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobPlanLogDo) Where(conds ...gen.Condition) IJobPlanLogDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobPlanLogDo) Order(conds ...field.Expr) IJobPlanLogDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobPlanLogDo) Distinct(cols ...field.Expr) IJobPlanLogDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobPlanLogDo) Omit(cols ...field.Expr) IJobPlanLogDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobPlanLogDo) Join(table schema.Tabler, on ...field.Expr) IJobPlanLogDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobPlanLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobPlanLogDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobPlanLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobPlanLogDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobPlanLogDo) Group(cols ...field.Expr) IJobPlanLogDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobPlanLogDo) Having(conds ...gen.Condition) IJobPlanLogDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobPlanLogDo) Limit(limit int) IJobPlanLogDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobPlanLogDo) Offset(offset int) IJobPlanLogDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobPlanLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobPlanLogDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobPlanLogDo) Unscoped() IJobPlanLogDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobPlanLogDo) Create(values ...*model.JobPlanLog) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobPlanLogDo) CreateInBatches(values []*model.JobPlanLog, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobPlanLogDo) Save(values ...*model.JobPlanLog) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobPlanLogDo) First() (*model.JobPlanLog, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanLog), nil
	}
}

func (j jobPlanLogDo) Take() (*model.JobPlanLog, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanLog), nil
	}
}

func (j jobPlanLogDo) Last() (*model.JobPlanLog, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanLog), nil
	}
}

func (j jobPlanLogDo) Find() ([]*model.JobPlanLog, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobPlanLog), err
}

func (j jobPlanLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobPlanLog, err error) {
	buf := make([]*model.JobPlanLog, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobPlanLogDo) FindInBatches(result *[]*model.JobPlanLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobPlanLogDo) Attrs(attrs ...field.AssignExpr) IJobPlanLogDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobPlanLogDo) Assign(attrs ...field.AssignExpr) IJobPlanLogDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobPlanLogDo) Joins(fields ...field.RelationField) IJobPlanLogDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobPlanLogDo) Preload(fields ...field.RelationField) IJobPlanLogDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobPlanLogDo) FirstOrInit() (*model.JobPlanLog, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanLog), nil
	}
}

func (j jobPlanLogDo) FirstOrCreate() (*model.JobPlanLog, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobPlanLog), nil
	}
}

func (j jobPlanLogDo) FindByPage(offset int, limit int) (result []*model.JobPlanLog, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobPlanLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobPlanLogDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobPlanLogDo) Delete(models ...*model.JobPlanLog) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobPlanLogDo) withDO(do gen.Dao) *jobPlanLogDo {
	j.DO = *do.(*gen.DO)
	return j
}
