// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newJobScript(db *gorm.DB, opts ...gen.DOOption) jobScript {
	_jobScript := jobScript{}

	_jobScript.jobScriptDo.UseDB(db, opts...)
	_jobScript.jobScriptDo.UseModel(&model.JobScript{})

	tableName := _jobScript.jobScriptDo.TableName()
	_jobScript.ALL = field.NewAsterisk(tableName)
	_jobScript.ID = field.NewUint32(tableName, "id")
	_jobScript.Name = field.NewString(tableName, "name")
	_jobScript.Type = field.NewString(tableName, "type")
	_jobScript.Category = field.NewString(tableName, "category")
	_jobScript.Content = field.NewString(tableName, "content")
	_jobScript.Parameters = field.NewString(tableName, "parameters")
	_jobScript.Timeout = field.NewUint32(tableName, "timeout")
	_jobScript.WorkDir = field.NewString(tableName, "work_dir")
	_jobScript.Env = field.NewString(tableName, "env")
	_jobScript.CreatedAt = field.NewTime(tableName, "created_at")
	_jobScript.UpdatedAt = field.NewTime(tableName, "updated_at")
	_jobScript.DeletedAt = field.NewField(tableName, "deleted_at")

	_jobScript.fillFieldMap()

	return _jobScript
}

// jobScript 脚本
type jobScript struct {
	jobScriptDo

	ALL        field.Asterisk
	ID         field.Uint32 // 主键id
	Name       field.String // 脚本名称
	Type       field.String // 类型
	Category   field.String // 类别，默认是default
	Content    field.String // 脚本内容
	Parameters field.String // 脚本参数
	Timeout    field.Uint32 // 超时时间
	WorkDir    field.String // 工作路径
	Env        field.String // 环境变量
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	DeletedAt  field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (j jobScript) Table(newTableName string) *jobScript {
	j.jobScriptDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j jobScript) As(alias string) *jobScript {
	j.jobScriptDo.DO = *(j.jobScriptDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *jobScript) updateTableName(table string) *jobScript {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewUint32(table, "id")
	j.Name = field.NewString(table, "name")
	j.Type = field.NewString(table, "type")
	j.Category = field.NewString(table, "category")
	j.Content = field.NewString(table, "content")
	j.Parameters = field.NewString(table, "parameters")
	j.Timeout = field.NewUint32(table, "timeout")
	j.WorkDir = field.NewString(table, "work_dir")
	j.Env = field.NewString(table, "env")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.DeletedAt = field.NewField(table, "deleted_at")

	j.fillFieldMap()

	return j
}

func (j *jobScript) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *jobScript) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 12)
	j.fieldMap["id"] = j.ID
	j.fieldMap["name"] = j.Name
	j.fieldMap["type"] = j.Type
	j.fieldMap["category"] = j.Category
	j.fieldMap["content"] = j.Content
	j.fieldMap["parameters"] = j.Parameters
	j.fieldMap["timeout"] = j.Timeout
	j.fieldMap["work_dir"] = j.WorkDir
	j.fieldMap["env"] = j.Env
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["deleted_at"] = j.DeletedAt
}

func (j jobScript) clone(db *gorm.DB) jobScript {
	j.jobScriptDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j jobScript) replaceDB(db *gorm.DB) jobScript {
	j.jobScriptDo.ReplaceDB(db)
	return j
}

type jobScriptDo struct{ gen.DO }

type IJobScriptDo interface {
	gen.SubQuery
	Debug() IJobScriptDo
	WithContext(ctx context.Context) IJobScriptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJobScriptDo
	WriteDB() IJobScriptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJobScriptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJobScriptDo
	Not(conds ...gen.Condition) IJobScriptDo
	Or(conds ...gen.Condition) IJobScriptDo
	Select(conds ...field.Expr) IJobScriptDo
	Where(conds ...gen.Condition) IJobScriptDo
	Order(conds ...field.Expr) IJobScriptDo
	Distinct(cols ...field.Expr) IJobScriptDo
	Omit(cols ...field.Expr) IJobScriptDo
	Join(table schema.Tabler, on ...field.Expr) IJobScriptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJobScriptDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJobScriptDo
	Group(cols ...field.Expr) IJobScriptDo
	Having(conds ...gen.Condition) IJobScriptDo
	Limit(limit int) IJobScriptDo
	Offset(offset int) IJobScriptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJobScriptDo
	Unscoped() IJobScriptDo
	Create(values ...*model.JobScript) error
	CreateInBatches(values []*model.JobScript, batchSize int) error
	Save(values ...*model.JobScript) error
	First() (*model.JobScript, error)
	Take() (*model.JobScript, error)
	Last() (*model.JobScript, error)
	Find() ([]*model.JobScript, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobScript, err error)
	FindInBatches(result *[]*model.JobScript, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.JobScript) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJobScriptDo
	Assign(attrs ...field.AssignExpr) IJobScriptDo
	Joins(fields ...field.RelationField) IJobScriptDo
	Preload(fields ...field.RelationField) IJobScriptDo
	FirstOrInit() (*model.JobScript, error)
	FirstOrCreate() (*model.JobScript, error)
	FindByPage(offset int, limit int) (result []*model.JobScript, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJobScriptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (j jobScriptDo) Debug() IJobScriptDo {
	return j.withDO(j.DO.Debug())
}

func (j jobScriptDo) WithContext(ctx context.Context) IJobScriptDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j jobScriptDo) ReadDB() IJobScriptDo {
	return j.Clauses(dbresolver.Read)
}

func (j jobScriptDo) WriteDB() IJobScriptDo {
	return j.Clauses(dbresolver.Write)
}

func (j jobScriptDo) Session(config *gorm.Session) IJobScriptDo {
	return j.withDO(j.DO.Session(config))
}

func (j jobScriptDo) Clauses(conds ...clause.Expression) IJobScriptDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j jobScriptDo) Returning(value interface{}, columns ...string) IJobScriptDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j jobScriptDo) Not(conds ...gen.Condition) IJobScriptDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j jobScriptDo) Or(conds ...gen.Condition) IJobScriptDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j jobScriptDo) Select(conds ...field.Expr) IJobScriptDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j jobScriptDo) Where(conds ...gen.Condition) IJobScriptDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j jobScriptDo) Order(conds ...field.Expr) IJobScriptDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j jobScriptDo) Distinct(cols ...field.Expr) IJobScriptDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j jobScriptDo) Omit(cols ...field.Expr) IJobScriptDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j jobScriptDo) Join(table schema.Tabler, on ...field.Expr) IJobScriptDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j jobScriptDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJobScriptDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j jobScriptDo) RightJoin(table schema.Tabler, on ...field.Expr) IJobScriptDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j jobScriptDo) Group(cols ...field.Expr) IJobScriptDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j jobScriptDo) Having(conds ...gen.Condition) IJobScriptDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j jobScriptDo) Limit(limit int) IJobScriptDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j jobScriptDo) Offset(offset int) IJobScriptDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j jobScriptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJobScriptDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j jobScriptDo) Unscoped() IJobScriptDo {
	return j.withDO(j.DO.Unscoped())
}

func (j jobScriptDo) Create(values ...*model.JobScript) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j jobScriptDo) CreateInBatches(values []*model.JobScript, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j jobScriptDo) Save(values ...*model.JobScript) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j jobScriptDo) First() (*model.JobScript, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScript), nil
	}
}

func (j jobScriptDo) Take() (*model.JobScript, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScript), nil
	}
}

func (j jobScriptDo) Last() (*model.JobScript, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScript), nil
	}
}

func (j jobScriptDo) Find() ([]*model.JobScript, error) {
	result, err := j.DO.Find()
	return result.([]*model.JobScript), err
}

func (j jobScriptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.JobScript, err error) {
	buf := make([]*model.JobScript, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j jobScriptDo) FindInBatches(result *[]*model.JobScript, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j jobScriptDo) Attrs(attrs ...field.AssignExpr) IJobScriptDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j jobScriptDo) Assign(attrs ...field.AssignExpr) IJobScriptDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j jobScriptDo) Joins(fields ...field.RelationField) IJobScriptDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j jobScriptDo) Preload(fields ...field.RelationField) IJobScriptDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j jobScriptDo) FirstOrInit() (*model.JobScript, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScript), nil
	}
}

func (j jobScriptDo) FirstOrCreate() (*model.JobScript, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.JobScript), nil
	}
}

func (j jobScriptDo) FindByPage(offset int, limit int) (result []*model.JobScript, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j jobScriptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j jobScriptDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j jobScriptDo) Delete(models ...*model.JobScript) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *jobScriptDo) withDO(do gen.Dao) *jobScriptDo {
	j.DO = *do.(*gen.DO)
	return j
}
