// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newSystemDictType(db *gorm.DB, opts ...gen.DOOption) systemDictType {
	_systemDictType := systemDictType{}

	_systemDictType.systemDictTypeDo.UseDB(db, opts...)
	_systemDictType.systemDictTypeDo.UseModel(&model.SystemDictType{})

	tableName := _systemDictType.systemDictTypeDo.TableName()
	_systemDictType.ALL = field.NewAsterisk(tableName)
	_systemDictType.ID = field.NewInt64(tableName, "id")
	_systemDictType.Name = field.NewString(tableName, "name")
	_systemDictType.Type = field.NewString(tableName, "type")
	_systemDictType.Status = field.NewInt32(tableName, "status")
	_systemDictType.Remark = field.NewString(tableName, "remark")
	_systemDictType.Creator = field.NewString(tableName, "creator")
	_systemDictType.CreateAt = field.NewTime(tableName, "create_at")
	_systemDictType.Updater = field.NewString(tableName, "updater")
	_systemDictType.UpdateAt = field.NewTime(tableName, "update_at")
	_systemDictType.DeletedAt = field.NewField(tableName, "deleted_at")

	_systemDictType.fillFieldMap()

	return _systemDictType
}

// systemDictType 字典类型表
type systemDictType struct {
	systemDictTypeDo

	ALL       field.Asterisk
	ID        field.Int64  // 字典主键
	Name      field.String // 字典名称
	Type      field.String // 字典类型
	Status    field.Int32  // 状态（0正常 1停用）
	Remark    field.String // 备注
	Creator   field.String // 创建者
	CreateAt  field.Time   // 创建时间
	Updater   field.String // 更新者
	UpdateAt  field.Time   // 更新时间
	DeletedAt field.Field  // 删除字段

	fieldMap map[string]field.Expr
}

func (s systemDictType) Table(newTableName string) *systemDictType {
	s.systemDictTypeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemDictType) As(alias string) *systemDictType {
	s.systemDictTypeDo.DO = *(s.systemDictTypeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemDictType) updateTableName(table string) *systemDictType {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Type = field.NewString(table, "type")
	s.Status = field.NewInt32(table, "status")
	s.Remark = field.NewString(table, "remark")
	s.Creator = field.NewString(table, "creator")
	s.CreateAt = field.NewTime(table, "create_at")
	s.Updater = field.NewString(table, "updater")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *systemDictType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemDictType) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["type"] = s.Type
	s.fieldMap["status"] = s.Status
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s systemDictType) clone(db *gorm.DB) systemDictType {
	s.systemDictTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemDictType) replaceDB(db *gorm.DB) systemDictType {
	s.systemDictTypeDo.ReplaceDB(db)
	return s
}

type systemDictTypeDo struct{ gen.DO }

type ISystemDictTypeDo interface {
	gen.SubQuery
	Debug() ISystemDictTypeDo
	WithContext(ctx context.Context) ISystemDictTypeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemDictTypeDo
	WriteDB() ISystemDictTypeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemDictTypeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemDictTypeDo
	Not(conds ...gen.Condition) ISystemDictTypeDo
	Or(conds ...gen.Condition) ISystemDictTypeDo
	Select(conds ...field.Expr) ISystemDictTypeDo
	Where(conds ...gen.Condition) ISystemDictTypeDo
	Order(conds ...field.Expr) ISystemDictTypeDo
	Distinct(cols ...field.Expr) ISystemDictTypeDo
	Omit(cols ...field.Expr) ISystemDictTypeDo
	Join(table schema.Tabler, on ...field.Expr) ISystemDictTypeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemDictTypeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemDictTypeDo
	Group(cols ...field.Expr) ISystemDictTypeDo
	Having(conds ...gen.Condition) ISystemDictTypeDo
	Limit(limit int) ISystemDictTypeDo
	Offset(offset int) ISystemDictTypeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemDictTypeDo
	Unscoped() ISystemDictTypeDo
	Create(values ...*model.SystemDictType) error
	CreateInBatches(values []*model.SystemDictType, batchSize int) error
	Save(values ...*model.SystemDictType) error
	First() (*model.SystemDictType, error)
	Take() (*model.SystemDictType, error)
	Last() (*model.SystemDictType, error)
	Find() ([]*model.SystemDictType, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDictType, err error)
	FindInBatches(result *[]*model.SystemDictType, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemDictType) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemDictTypeDo
	Assign(attrs ...field.AssignExpr) ISystemDictTypeDo
	Joins(fields ...field.RelationField) ISystemDictTypeDo
	Preload(fields ...field.RelationField) ISystemDictTypeDo
	FirstOrInit() (*model.SystemDictType, error)
	FirstOrCreate() (*model.SystemDictType, error)
	FindByPage(offset int, limit int) (result []*model.SystemDictType, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemDictTypeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemDictTypeDo) Debug() ISystemDictTypeDo {
	return s.withDO(s.DO.Debug())
}

func (s systemDictTypeDo) WithContext(ctx context.Context) ISystemDictTypeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemDictTypeDo) ReadDB() ISystemDictTypeDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemDictTypeDo) WriteDB() ISystemDictTypeDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemDictTypeDo) Session(config *gorm.Session) ISystemDictTypeDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemDictTypeDo) Clauses(conds ...clause.Expression) ISystemDictTypeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemDictTypeDo) Returning(value interface{}, columns ...string) ISystemDictTypeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemDictTypeDo) Not(conds ...gen.Condition) ISystemDictTypeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemDictTypeDo) Or(conds ...gen.Condition) ISystemDictTypeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemDictTypeDo) Select(conds ...field.Expr) ISystemDictTypeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemDictTypeDo) Where(conds ...gen.Condition) ISystemDictTypeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemDictTypeDo) Order(conds ...field.Expr) ISystemDictTypeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemDictTypeDo) Distinct(cols ...field.Expr) ISystemDictTypeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemDictTypeDo) Omit(cols ...field.Expr) ISystemDictTypeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemDictTypeDo) Join(table schema.Tabler, on ...field.Expr) ISystemDictTypeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemDictTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemDictTypeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemDictTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemDictTypeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemDictTypeDo) Group(cols ...field.Expr) ISystemDictTypeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemDictTypeDo) Having(conds ...gen.Condition) ISystemDictTypeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemDictTypeDo) Limit(limit int) ISystemDictTypeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemDictTypeDo) Offset(offset int) ISystemDictTypeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemDictTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemDictTypeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemDictTypeDo) Unscoped() ISystemDictTypeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemDictTypeDo) Create(values ...*model.SystemDictType) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemDictTypeDo) CreateInBatches(values []*model.SystemDictType, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemDictTypeDo) Save(values ...*model.SystemDictType) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemDictTypeDo) First() (*model.SystemDictType, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictType), nil
	}
}

func (s systemDictTypeDo) Take() (*model.SystemDictType, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictType), nil
	}
}

func (s systemDictTypeDo) Last() (*model.SystemDictType, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictType), nil
	}
}

func (s systemDictTypeDo) Find() ([]*model.SystemDictType, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemDictType), err
}

func (s systemDictTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDictType, err error) {
	buf := make([]*model.SystemDictType, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemDictTypeDo) FindInBatches(result *[]*model.SystemDictType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemDictTypeDo) Attrs(attrs ...field.AssignExpr) ISystemDictTypeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemDictTypeDo) Assign(attrs ...field.AssignExpr) ISystemDictTypeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemDictTypeDo) Joins(fields ...field.RelationField) ISystemDictTypeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemDictTypeDo) Preload(fields ...field.RelationField) ISystemDictTypeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemDictTypeDo) FirstOrInit() (*model.SystemDictType, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictType), nil
	}
}

func (s systemDictTypeDo) FirstOrCreate() (*model.SystemDictType, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictType), nil
	}
}

func (s systemDictTypeDo) FindByPage(offset int, limit int) (result []*model.SystemDictType, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemDictTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemDictTypeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemDictTypeDo) Delete(models ...*model.SystemDictType) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemDictTypeDo) withDO(do gen.Dao) *systemDictTypeDo {
	s.DO = *do.(*gen.DO)
	return s
}
