// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newSystemDictDatum(db *gorm.DB, opts ...gen.DOOption) systemDictDatum {
	_systemDictDatum := systemDictDatum{}

	_systemDictDatum.systemDictDatumDo.UseDB(db, opts...)
	_systemDictDatum.systemDictDatumDo.UseModel(&model.SystemDictDatum{})

	tableName := _systemDictDatum.systemDictDatumDo.TableName()
	_systemDictDatum.ALL = field.NewAsterisk(tableName)
	_systemDictDatum.ID = field.NewInt64(tableName, "id")
	_systemDictDatum.Sort = field.NewInt32(tableName, "sort")
	_systemDictDatum.Label = field.NewString(tableName, "label")
	_systemDictDatum.Value = field.NewString(tableName, "value")
	_systemDictDatum.DictType = field.NewString(tableName, "dict_type")
	_systemDictDatum.Status = field.NewInt32(tableName, "status")
	_systemDictDatum.ColorType = field.NewString(tableName, "color_type")
	_systemDictDatum.CSSClass = field.NewString(tableName, "css_class")
	_systemDictDatum.Remark = field.NewString(tableName, "remark")
	_systemDictDatum.Creator = field.NewString(tableName, "creator")
	_systemDictDatum.CreateAt = field.NewTime(tableName, "create_at")
	_systemDictDatum.Updater = field.NewString(tableName, "updater")
	_systemDictDatum.UpdateAt = field.NewTime(tableName, "update_at")
	_systemDictDatum.DeletedAt = field.NewField(tableName, "deleted_at")

	_systemDictDatum.fillFieldMap()

	return _systemDictDatum
}

// systemDictDatum 字典数据表
type systemDictDatum struct {
	systemDictDatumDo

	ALL       field.Asterisk
	ID        field.Int64  // 字典编码
	Sort      field.Int32  // 字典排序
	Label     field.String // 字典标签
	Value     field.String // 字典键值
	DictType  field.String // 字典类型
	Status    field.Int32  // 状态（0正常 1停用）
	ColorType field.String // 颜色类型
	CSSClass  field.String // css 样式
	Remark    field.String // 备注
	Creator   field.String // 创建者
	CreateAt  field.Time   // 创建时间
	Updater   field.String // 更新者
	UpdateAt  field.Time   // 更新时间
	DeletedAt field.Field  // 删除字段

	fieldMap map[string]field.Expr
}

func (s systemDictDatum) Table(newTableName string) *systemDictDatum {
	s.systemDictDatumDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemDictDatum) As(alias string) *systemDictDatum {
	s.systemDictDatumDo.DO = *(s.systemDictDatumDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemDictDatum) updateTableName(table string) *systemDictDatum {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Sort = field.NewInt32(table, "sort")
	s.Label = field.NewString(table, "label")
	s.Value = field.NewString(table, "value")
	s.DictType = field.NewString(table, "dict_type")
	s.Status = field.NewInt32(table, "status")
	s.ColorType = field.NewString(table, "color_type")
	s.CSSClass = field.NewString(table, "css_class")
	s.Remark = field.NewString(table, "remark")
	s.Creator = field.NewString(table, "creator")
	s.CreateAt = field.NewTime(table, "create_at")
	s.Updater = field.NewString(table, "updater")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *systemDictDatum) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemDictDatum) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["label"] = s.Label
	s.fieldMap["value"] = s.Value
	s.fieldMap["dict_type"] = s.DictType
	s.fieldMap["status"] = s.Status
	s.fieldMap["color_type"] = s.ColorType
	s.fieldMap["css_class"] = s.CSSClass
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s systemDictDatum) clone(db *gorm.DB) systemDictDatum {
	s.systemDictDatumDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemDictDatum) replaceDB(db *gorm.DB) systemDictDatum {
	s.systemDictDatumDo.ReplaceDB(db)
	return s
}

type systemDictDatumDo struct{ gen.DO }

type ISystemDictDatumDo interface {
	gen.SubQuery
	Debug() ISystemDictDatumDo
	WithContext(ctx context.Context) ISystemDictDatumDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemDictDatumDo
	WriteDB() ISystemDictDatumDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemDictDatumDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemDictDatumDo
	Not(conds ...gen.Condition) ISystemDictDatumDo
	Or(conds ...gen.Condition) ISystemDictDatumDo
	Select(conds ...field.Expr) ISystemDictDatumDo
	Where(conds ...gen.Condition) ISystemDictDatumDo
	Order(conds ...field.Expr) ISystemDictDatumDo
	Distinct(cols ...field.Expr) ISystemDictDatumDo
	Omit(cols ...field.Expr) ISystemDictDatumDo
	Join(table schema.Tabler, on ...field.Expr) ISystemDictDatumDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemDictDatumDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemDictDatumDo
	Group(cols ...field.Expr) ISystemDictDatumDo
	Having(conds ...gen.Condition) ISystemDictDatumDo
	Limit(limit int) ISystemDictDatumDo
	Offset(offset int) ISystemDictDatumDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemDictDatumDo
	Unscoped() ISystemDictDatumDo
	Create(values ...*model.SystemDictDatum) error
	CreateInBatches(values []*model.SystemDictDatum, batchSize int) error
	Save(values ...*model.SystemDictDatum) error
	First() (*model.SystemDictDatum, error)
	Take() (*model.SystemDictDatum, error)
	Last() (*model.SystemDictDatum, error)
	Find() ([]*model.SystemDictDatum, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDictDatum, err error)
	FindInBatches(result *[]*model.SystemDictDatum, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemDictDatum) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemDictDatumDo
	Assign(attrs ...field.AssignExpr) ISystemDictDatumDo
	Joins(fields ...field.RelationField) ISystemDictDatumDo
	Preload(fields ...field.RelationField) ISystemDictDatumDo
	FirstOrInit() (*model.SystemDictDatum, error)
	FirstOrCreate() (*model.SystemDictDatum, error)
	FindByPage(offset int, limit int) (result []*model.SystemDictDatum, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemDictDatumDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemDictDatumDo) Debug() ISystemDictDatumDo {
	return s.withDO(s.DO.Debug())
}

func (s systemDictDatumDo) WithContext(ctx context.Context) ISystemDictDatumDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemDictDatumDo) ReadDB() ISystemDictDatumDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemDictDatumDo) WriteDB() ISystemDictDatumDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemDictDatumDo) Session(config *gorm.Session) ISystemDictDatumDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemDictDatumDo) Clauses(conds ...clause.Expression) ISystemDictDatumDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemDictDatumDo) Returning(value interface{}, columns ...string) ISystemDictDatumDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemDictDatumDo) Not(conds ...gen.Condition) ISystemDictDatumDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemDictDatumDo) Or(conds ...gen.Condition) ISystemDictDatumDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemDictDatumDo) Select(conds ...field.Expr) ISystemDictDatumDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemDictDatumDo) Where(conds ...gen.Condition) ISystemDictDatumDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemDictDatumDo) Order(conds ...field.Expr) ISystemDictDatumDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemDictDatumDo) Distinct(cols ...field.Expr) ISystemDictDatumDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemDictDatumDo) Omit(cols ...field.Expr) ISystemDictDatumDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemDictDatumDo) Join(table schema.Tabler, on ...field.Expr) ISystemDictDatumDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemDictDatumDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemDictDatumDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemDictDatumDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemDictDatumDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemDictDatumDo) Group(cols ...field.Expr) ISystemDictDatumDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemDictDatumDo) Having(conds ...gen.Condition) ISystemDictDatumDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemDictDatumDo) Limit(limit int) ISystemDictDatumDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemDictDatumDo) Offset(offset int) ISystemDictDatumDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemDictDatumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemDictDatumDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemDictDatumDo) Unscoped() ISystemDictDatumDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemDictDatumDo) Create(values ...*model.SystemDictDatum) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemDictDatumDo) CreateInBatches(values []*model.SystemDictDatum, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemDictDatumDo) Save(values ...*model.SystemDictDatum) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemDictDatumDo) First() (*model.SystemDictDatum, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictDatum), nil
	}
}

func (s systemDictDatumDo) Take() (*model.SystemDictDatum, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictDatum), nil
	}
}

func (s systemDictDatumDo) Last() (*model.SystemDictDatum, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictDatum), nil
	}
}

func (s systemDictDatumDo) Find() ([]*model.SystemDictDatum, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemDictDatum), err
}

func (s systemDictDatumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDictDatum, err error) {
	buf := make([]*model.SystemDictDatum, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemDictDatumDo) FindInBatches(result *[]*model.SystemDictDatum, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemDictDatumDo) Attrs(attrs ...field.AssignExpr) ISystemDictDatumDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemDictDatumDo) Assign(attrs ...field.AssignExpr) ISystemDictDatumDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemDictDatumDo) Joins(fields ...field.RelationField) ISystemDictDatumDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemDictDatumDo) Preload(fields ...field.RelationField) ISystemDictDatumDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemDictDatumDo) FirstOrInit() (*model.SystemDictDatum, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictDatum), nil
	}
}

func (s systemDictDatumDo) FirstOrCreate() (*model.SystemDictDatum, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictDatum), nil
	}
}

func (s systemDictDatumDo) FindByPage(offset int, limit int) (result []*model.SystemDictDatum, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemDictDatumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemDictDatumDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemDictDatumDo) Delete(models ...*model.SystemDictDatum) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemDictDatumDo) withDO(do gen.Dao) *systemDictDatumDo {
	s.DO = *do.(*gen.DO)
	return s
}
