// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newSystemUserPost(db *gorm.DB, opts ...gen.DOOption) systemUserPost {
	_systemUserPost := systemUserPost{}

	_systemUserPost.systemUserPostDo.UseDB(db, opts...)
	_systemUserPost.systemUserPostDo.UseModel(&model.SystemUserPost{})

	tableName := _systemUserPost.systemUserPostDo.TableName()
	_systemUserPost.ALL = field.NewAsterisk(tableName)
	_systemUserPost.ID = field.NewInt64(tableName, "id")
	_systemUserPost.UserID = field.NewInt64(tableName, "user_id")
	_systemUserPost.PostID = field.NewInt64(tableName, "post_id")
	_systemUserPost.Creator = field.NewString(tableName, "creator")
	_systemUserPost.CreateAt = field.NewTime(tableName, "create_at")
	_systemUserPost.Updater = field.NewString(tableName, "updater")
	_systemUserPost.UpdateAt = field.NewTime(tableName, "update_at")
	_systemUserPost.DeletedAt = field.NewField(tableName, "deleted_at")

	_systemUserPost.fillFieldMap()

	return _systemUserPost
}

// systemUserPost 用户岗位表
type systemUserPost struct {
	systemUserPostDo

	ALL       field.Asterisk
	ID        field.Int64  // id
	UserID    field.Int64  // 用户ID
	PostID    field.Int64  // 岗位ID
	Creator   field.String // 创建者
	CreateAt  field.Time   // 创建时间
	Updater   field.String // 更新者
	UpdateAt  field.Time   // 更新时间
	DeletedAt field.Field  // 删除字段

	fieldMap map[string]field.Expr
}

func (s systemUserPost) Table(newTableName string) *systemUserPost {
	s.systemUserPostDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemUserPost) As(alias string) *systemUserPost {
	s.systemUserPostDo.DO = *(s.systemUserPostDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemUserPost) updateTableName(table string) *systemUserPost {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.UserID = field.NewInt64(table, "user_id")
	s.PostID = field.NewInt64(table, "post_id")
	s.Creator = field.NewString(table, "creator")
	s.CreateAt = field.NewTime(table, "create_at")
	s.Updater = field.NewString(table, "updater")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *systemUserPost) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemUserPost) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["post_id"] = s.PostID
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s systemUserPost) clone(db *gorm.DB) systemUserPost {
	s.systemUserPostDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemUserPost) replaceDB(db *gorm.DB) systemUserPost {
	s.systemUserPostDo.ReplaceDB(db)
	return s
}

type systemUserPostDo struct{ gen.DO }

type ISystemUserPostDo interface {
	gen.SubQuery
	Debug() ISystemUserPostDo
	WithContext(ctx context.Context) ISystemUserPostDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemUserPostDo
	WriteDB() ISystemUserPostDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemUserPostDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemUserPostDo
	Not(conds ...gen.Condition) ISystemUserPostDo
	Or(conds ...gen.Condition) ISystemUserPostDo
	Select(conds ...field.Expr) ISystemUserPostDo
	Where(conds ...gen.Condition) ISystemUserPostDo
	Order(conds ...field.Expr) ISystemUserPostDo
	Distinct(cols ...field.Expr) ISystemUserPostDo
	Omit(cols ...field.Expr) ISystemUserPostDo
	Join(table schema.Tabler, on ...field.Expr) ISystemUserPostDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemUserPostDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemUserPostDo
	Group(cols ...field.Expr) ISystemUserPostDo
	Having(conds ...gen.Condition) ISystemUserPostDo
	Limit(limit int) ISystemUserPostDo
	Offset(offset int) ISystemUserPostDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemUserPostDo
	Unscoped() ISystemUserPostDo
	Create(values ...*model.SystemUserPost) error
	CreateInBatches(values []*model.SystemUserPost, batchSize int) error
	Save(values ...*model.SystemUserPost) error
	First() (*model.SystemUserPost, error)
	Take() (*model.SystemUserPost, error)
	Last() (*model.SystemUserPost, error)
	Find() ([]*model.SystemUserPost, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemUserPost, err error)
	FindInBatches(result *[]*model.SystemUserPost, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemUserPost) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemUserPostDo
	Assign(attrs ...field.AssignExpr) ISystemUserPostDo
	Joins(fields ...field.RelationField) ISystemUserPostDo
	Preload(fields ...field.RelationField) ISystemUserPostDo
	FirstOrInit() (*model.SystemUserPost, error)
	FirstOrCreate() (*model.SystemUserPost, error)
	FindByPage(offset int, limit int) (result []*model.SystemUserPost, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemUserPostDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemUserPostDo) Debug() ISystemUserPostDo {
	return s.withDO(s.DO.Debug())
}

func (s systemUserPostDo) WithContext(ctx context.Context) ISystemUserPostDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemUserPostDo) ReadDB() ISystemUserPostDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemUserPostDo) WriteDB() ISystemUserPostDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemUserPostDo) Session(config *gorm.Session) ISystemUserPostDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemUserPostDo) Clauses(conds ...clause.Expression) ISystemUserPostDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemUserPostDo) Returning(value interface{}, columns ...string) ISystemUserPostDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemUserPostDo) Not(conds ...gen.Condition) ISystemUserPostDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemUserPostDo) Or(conds ...gen.Condition) ISystemUserPostDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemUserPostDo) Select(conds ...field.Expr) ISystemUserPostDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemUserPostDo) Where(conds ...gen.Condition) ISystemUserPostDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemUserPostDo) Order(conds ...field.Expr) ISystemUserPostDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemUserPostDo) Distinct(cols ...field.Expr) ISystemUserPostDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemUserPostDo) Omit(cols ...field.Expr) ISystemUserPostDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemUserPostDo) Join(table schema.Tabler, on ...field.Expr) ISystemUserPostDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemUserPostDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemUserPostDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemUserPostDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemUserPostDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemUserPostDo) Group(cols ...field.Expr) ISystemUserPostDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemUserPostDo) Having(conds ...gen.Condition) ISystemUserPostDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemUserPostDo) Limit(limit int) ISystemUserPostDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemUserPostDo) Offset(offset int) ISystemUserPostDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemUserPostDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemUserPostDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemUserPostDo) Unscoped() ISystemUserPostDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemUserPostDo) Create(values ...*model.SystemUserPost) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemUserPostDo) CreateInBatches(values []*model.SystemUserPost, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemUserPostDo) Save(values ...*model.SystemUserPost) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemUserPostDo) First() (*model.SystemUserPost, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserPost), nil
	}
}

func (s systemUserPostDo) Take() (*model.SystemUserPost, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserPost), nil
	}
}

func (s systemUserPostDo) Last() (*model.SystemUserPost, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserPost), nil
	}
}

func (s systemUserPostDo) Find() ([]*model.SystemUserPost, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemUserPost), err
}

func (s systemUserPostDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemUserPost, err error) {
	buf := make([]*model.SystemUserPost, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemUserPostDo) FindInBatches(result *[]*model.SystemUserPost, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemUserPostDo) Attrs(attrs ...field.AssignExpr) ISystemUserPostDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemUserPostDo) Assign(attrs ...field.AssignExpr) ISystemUserPostDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemUserPostDo) Joins(fields ...field.RelationField) ISystemUserPostDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemUserPostDo) Preload(fields ...field.RelationField) ISystemUserPostDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemUserPostDo) FirstOrInit() (*model.SystemUserPost, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserPost), nil
	}
}

func (s systemUserPostDo) FirstOrCreate() (*model.SystemUserPost, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemUserPost), nil
	}
}

func (s systemUserPostDo) FindByPage(offset int, limit int) (result []*model.SystemUserPost, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemUserPostDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemUserPostDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemUserPostDo) Delete(models ...*model.SystemUserPost) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemUserPostDo) withDO(do gen.Dao) *systemUserPostDo {
	s.DO = *do.(*gen.DO)
	return s
}
