// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newSystemOperateLog(db *gorm.DB, opts ...gen.DOOption) systemOperateLog {
	_systemOperateLog := systemOperateLog{}

	_systemOperateLog.systemOperateLogDo.UseDB(db, opts...)
	_systemOperateLog.systemOperateLogDo.UseModel(&model.SystemOperateLog{})

	tableName := _systemOperateLog.systemOperateLogDo.TableName()
	_systemOperateLog.ALL = field.NewAsterisk(tableName)
	_systemOperateLog.ID = field.NewInt64(tableName, "id")
	_systemOperateLog.TraceID = field.NewString(tableName, "trace_id")
	_systemOperateLog.UserID = field.NewInt64(tableName, "user_id")
	_systemOperateLog.UserType = field.NewInt32(tableName, "user_type")
	_systemOperateLog.Type = field.NewString(tableName, "type")
	_systemOperateLog.SubType = field.NewString(tableName, "sub_type")
	_systemOperateLog.BizID = field.NewInt64(tableName, "biz_id")
	_systemOperateLog.Action = field.NewString(tableName, "action")
	_systemOperateLog.Success = field.NewField(tableName, "success")
	_systemOperateLog.Extra = field.NewString(tableName, "extra")
	_systemOperateLog.RequestMethod = field.NewString(tableName, "request_method")
	_systemOperateLog.RequestURL = field.NewString(tableName, "request_url")
	_systemOperateLog.UserIP = field.NewString(tableName, "user_ip")
	_systemOperateLog.UserAgent = field.NewString(tableName, "user_agent")
	_systemOperateLog.Creator = field.NewString(tableName, "creator")
	_systemOperateLog.CreateAt = field.NewTime(tableName, "create_at")
	_systemOperateLog.Updater = field.NewString(tableName, "updater")
	_systemOperateLog.UpdateAt = field.NewTime(tableName, "update_at")
	_systemOperateLog.DeletedAt = field.NewField(tableName, "deleted_at")

	_systemOperateLog.fillFieldMap()

	return _systemOperateLog
}

// systemOperateLog 操作日志记录 V2 版本
type systemOperateLog struct {
	systemOperateLogDo

	ALL           field.Asterisk
	ID            field.Int64  // 日志主键
	TraceID       field.String // 链路追踪编号
	UserID        field.Int64  // 用户编号
	UserType      field.Int32  // 用户类型
	Type          field.String // 操作模块类型
	SubType       field.String // 操作名
	BizID         field.Int64  // 操作数据模块编号
	Action        field.String // 操作内容
	Success       field.Field  // 操作结果
	Extra         field.String // 拓展字段
	RequestMethod field.String // 请求方法名
	RequestURL    field.String // 请求地址
	UserIP        field.String // 用户 IP
	UserAgent     field.String // 浏览器 UA
	Creator       field.String // 创建者
	CreateAt      field.Time   // 创建时间
	Updater       field.String // 更新者
	UpdateAt      field.Time   // 更新时间
	DeletedAt     field.Field  // 删除字段

	fieldMap map[string]field.Expr
}

func (s systemOperateLog) Table(newTableName string) *systemOperateLog {
	s.systemOperateLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemOperateLog) As(alias string) *systemOperateLog {
	s.systemOperateLogDo.DO = *(s.systemOperateLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemOperateLog) updateTableName(table string) *systemOperateLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.TraceID = field.NewString(table, "trace_id")
	s.UserID = field.NewInt64(table, "user_id")
	s.UserType = field.NewInt32(table, "user_type")
	s.Type = field.NewString(table, "type")
	s.SubType = field.NewString(table, "sub_type")
	s.BizID = field.NewInt64(table, "biz_id")
	s.Action = field.NewString(table, "action")
	s.Success = field.NewField(table, "success")
	s.Extra = field.NewString(table, "extra")
	s.RequestMethod = field.NewString(table, "request_method")
	s.RequestURL = field.NewString(table, "request_url")
	s.UserIP = field.NewString(table, "user_ip")
	s.UserAgent = field.NewString(table, "user_agent")
	s.Creator = field.NewString(table, "creator")
	s.CreateAt = field.NewTime(table, "create_at")
	s.Updater = field.NewString(table, "updater")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *systemOperateLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemOperateLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 19)
	s.fieldMap["id"] = s.ID
	s.fieldMap["trace_id"] = s.TraceID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["user_type"] = s.UserType
	s.fieldMap["type"] = s.Type
	s.fieldMap["sub_type"] = s.SubType
	s.fieldMap["biz_id"] = s.BizID
	s.fieldMap["action"] = s.Action
	s.fieldMap["success"] = s.Success
	s.fieldMap["extra"] = s.Extra
	s.fieldMap["request_method"] = s.RequestMethod
	s.fieldMap["request_url"] = s.RequestURL
	s.fieldMap["user_ip"] = s.UserIP
	s.fieldMap["user_agent"] = s.UserAgent
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s systemOperateLog) clone(db *gorm.DB) systemOperateLog {
	s.systemOperateLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemOperateLog) replaceDB(db *gorm.DB) systemOperateLog {
	s.systemOperateLogDo.ReplaceDB(db)
	return s
}

type systemOperateLogDo struct{ gen.DO }

type ISystemOperateLogDo interface {
	gen.SubQuery
	Debug() ISystemOperateLogDo
	WithContext(ctx context.Context) ISystemOperateLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemOperateLogDo
	WriteDB() ISystemOperateLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemOperateLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemOperateLogDo
	Not(conds ...gen.Condition) ISystemOperateLogDo
	Or(conds ...gen.Condition) ISystemOperateLogDo
	Select(conds ...field.Expr) ISystemOperateLogDo
	Where(conds ...gen.Condition) ISystemOperateLogDo
	Order(conds ...field.Expr) ISystemOperateLogDo
	Distinct(cols ...field.Expr) ISystemOperateLogDo
	Omit(cols ...field.Expr) ISystemOperateLogDo
	Join(table schema.Tabler, on ...field.Expr) ISystemOperateLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemOperateLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemOperateLogDo
	Group(cols ...field.Expr) ISystemOperateLogDo
	Having(conds ...gen.Condition) ISystemOperateLogDo
	Limit(limit int) ISystemOperateLogDo
	Offset(offset int) ISystemOperateLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemOperateLogDo
	Unscoped() ISystemOperateLogDo
	Create(values ...*model.SystemOperateLog) error
	CreateInBatches(values []*model.SystemOperateLog, batchSize int) error
	Save(values ...*model.SystemOperateLog) error
	First() (*model.SystemOperateLog, error)
	Take() (*model.SystemOperateLog, error)
	Last() (*model.SystemOperateLog, error)
	Find() ([]*model.SystemOperateLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemOperateLog, err error)
	FindInBatches(result *[]*model.SystemOperateLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemOperateLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemOperateLogDo
	Assign(attrs ...field.AssignExpr) ISystemOperateLogDo
	Joins(fields ...field.RelationField) ISystemOperateLogDo
	Preload(fields ...field.RelationField) ISystemOperateLogDo
	FirstOrInit() (*model.SystemOperateLog, error)
	FirstOrCreate() (*model.SystemOperateLog, error)
	FindByPage(offset int, limit int) (result []*model.SystemOperateLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemOperateLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemOperateLogDo) Debug() ISystemOperateLogDo {
	return s.withDO(s.DO.Debug())
}

func (s systemOperateLogDo) WithContext(ctx context.Context) ISystemOperateLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemOperateLogDo) ReadDB() ISystemOperateLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemOperateLogDo) WriteDB() ISystemOperateLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemOperateLogDo) Session(config *gorm.Session) ISystemOperateLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemOperateLogDo) Clauses(conds ...clause.Expression) ISystemOperateLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemOperateLogDo) Returning(value interface{}, columns ...string) ISystemOperateLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemOperateLogDo) Not(conds ...gen.Condition) ISystemOperateLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemOperateLogDo) Or(conds ...gen.Condition) ISystemOperateLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemOperateLogDo) Select(conds ...field.Expr) ISystemOperateLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemOperateLogDo) Where(conds ...gen.Condition) ISystemOperateLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemOperateLogDo) Order(conds ...field.Expr) ISystemOperateLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemOperateLogDo) Distinct(cols ...field.Expr) ISystemOperateLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemOperateLogDo) Omit(cols ...field.Expr) ISystemOperateLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemOperateLogDo) Join(table schema.Tabler, on ...field.Expr) ISystemOperateLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemOperateLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemOperateLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemOperateLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemOperateLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemOperateLogDo) Group(cols ...field.Expr) ISystemOperateLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemOperateLogDo) Having(conds ...gen.Condition) ISystemOperateLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemOperateLogDo) Limit(limit int) ISystemOperateLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemOperateLogDo) Offset(offset int) ISystemOperateLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemOperateLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemOperateLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemOperateLogDo) Unscoped() ISystemOperateLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemOperateLogDo) Create(values ...*model.SystemOperateLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemOperateLogDo) CreateInBatches(values []*model.SystemOperateLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemOperateLogDo) Save(values ...*model.SystemOperateLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemOperateLogDo) First() (*model.SystemOperateLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOperateLog), nil
	}
}

func (s systemOperateLogDo) Take() (*model.SystemOperateLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOperateLog), nil
	}
}

func (s systemOperateLogDo) Last() (*model.SystemOperateLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOperateLog), nil
	}
}

func (s systemOperateLogDo) Find() ([]*model.SystemOperateLog, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemOperateLog), err
}

func (s systemOperateLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemOperateLog, err error) {
	buf := make([]*model.SystemOperateLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemOperateLogDo) FindInBatches(result *[]*model.SystemOperateLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemOperateLogDo) Attrs(attrs ...field.AssignExpr) ISystemOperateLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemOperateLogDo) Assign(attrs ...field.AssignExpr) ISystemOperateLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemOperateLogDo) Joins(fields ...field.RelationField) ISystemOperateLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemOperateLogDo) Preload(fields ...field.RelationField) ISystemOperateLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemOperateLogDo) FirstOrInit() (*model.SystemOperateLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOperateLog), nil
	}
}

func (s systemOperateLogDo) FirstOrCreate() (*model.SystemOperateLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOperateLog), nil
	}
}

func (s systemOperateLogDo) FindByPage(offset int, limit int) (result []*model.SystemOperateLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemOperateLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemOperateLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemOperateLogDo) Delete(models ...*model.SystemOperateLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemOperateLogDo) withDO(do gen.Dao) *systemOperateLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
