// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newSystemOauth2RefreshToken(db *gorm.DB, opts ...gen.DOOption) systemOauth2RefreshToken {
	_systemOauth2RefreshToken := systemOauth2RefreshToken{}

	_systemOauth2RefreshToken.systemOauth2RefreshTokenDo.UseDB(db, opts...)
	_systemOauth2RefreshToken.systemOauth2RefreshTokenDo.UseModel(&model.SystemOauth2RefreshToken{})

	tableName := _systemOauth2RefreshToken.systemOauth2RefreshTokenDo.TableName()
	_systemOauth2RefreshToken.ALL = field.NewAsterisk(tableName)
	_systemOauth2RefreshToken.ID = field.NewInt64(tableName, "id")
	_systemOauth2RefreshToken.UserID = field.NewInt64(tableName, "user_id")
	_systemOauth2RefreshToken.RefreshToken = field.NewString(tableName, "refresh_token")
	_systemOauth2RefreshToken.UserType = field.NewInt32(tableName, "user_type")
	_systemOauth2RefreshToken.ClientID = field.NewString(tableName, "client_id")
	_systemOauth2RefreshToken.Scopes_ = field.NewString(tableName, "scopes")
	_systemOauth2RefreshToken.ExpiresTime = field.NewTime(tableName, "expires_time")
	_systemOauth2RefreshToken.Creator = field.NewString(tableName, "creator")
	_systemOauth2RefreshToken.CreateAt = field.NewTime(tableName, "create_at")
	_systemOauth2RefreshToken.Updater = field.NewString(tableName, "updater")
	_systemOauth2RefreshToken.UpdateAt = field.NewTime(tableName, "update_at")
	_systemOauth2RefreshToken.DeletedAt = field.NewField(tableName, "deleted_at")

	_systemOauth2RefreshToken.fillFieldMap()

	return _systemOauth2RefreshToken
}

// systemOauth2RefreshToken OAuth2 刷新令牌
type systemOauth2RefreshToken struct {
	systemOauth2RefreshTokenDo

	ALL          field.Asterisk
	ID           field.Int64  // 编号
	UserID       field.Int64  // 用户编号
	RefreshToken field.String // 刷新令牌
	UserType     field.Int32  // 用户类型
	ClientID     field.String // 客户端编号
	Scopes_      field.String // 授权范围
	ExpiresTime  field.Time   // 过期时间
	Creator      field.String // 创建者
	CreateAt     field.Time   // 创建时间
	Updater      field.String // 更新者
	UpdateAt     field.Time   // 更新时间
	DeletedAt    field.Field  // 删除字段

	fieldMap map[string]field.Expr
}

func (s systemOauth2RefreshToken) Table(newTableName string) *systemOauth2RefreshToken {
	s.systemOauth2RefreshTokenDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemOauth2RefreshToken) As(alias string) *systemOauth2RefreshToken {
	s.systemOauth2RefreshTokenDo.DO = *(s.systemOauth2RefreshTokenDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemOauth2RefreshToken) updateTableName(table string) *systemOauth2RefreshToken {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.UserID = field.NewInt64(table, "user_id")
	s.RefreshToken = field.NewString(table, "refresh_token")
	s.UserType = field.NewInt32(table, "user_type")
	s.ClientID = field.NewString(table, "client_id")
	s.Scopes_ = field.NewString(table, "scopes")
	s.ExpiresTime = field.NewTime(table, "expires_time")
	s.Creator = field.NewString(table, "creator")
	s.CreateAt = field.NewTime(table, "create_at")
	s.Updater = field.NewString(table, "updater")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *systemOauth2RefreshToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemOauth2RefreshToken) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["refresh_token"] = s.RefreshToken
	s.fieldMap["user_type"] = s.UserType
	s.fieldMap["client_id"] = s.ClientID
	s.fieldMap["scopes"] = s.Scopes_
	s.fieldMap["expires_time"] = s.ExpiresTime
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s systemOauth2RefreshToken) clone(db *gorm.DB) systemOauth2RefreshToken {
	s.systemOauth2RefreshTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemOauth2RefreshToken) replaceDB(db *gorm.DB) systemOauth2RefreshToken {
	s.systemOauth2RefreshTokenDo.ReplaceDB(db)
	return s
}

type systemOauth2RefreshTokenDo struct{ gen.DO }

type ISystemOauth2RefreshTokenDo interface {
	gen.SubQuery
	Debug() ISystemOauth2RefreshTokenDo
	WithContext(ctx context.Context) ISystemOauth2RefreshTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemOauth2RefreshTokenDo
	WriteDB() ISystemOauth2RefreshTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemOauth2RefreshTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemOauth2RefreshTokenDo
	Not(conds ...gen.Condition) ISystemOauth2RefreshTokenDo
	Or(conds ...gen.Condition) ISystemOauth2RefreshTokenDo
	Select(conds ...field.Expr) ISystemOauth2RefreshTokenDo
	Where(conds ...gen.Condition) ISystemOauth2RefreshTokenDo
	Order(conds ...field.Expr) ISystemOauth2RefreshTokenDo
	Distinct(cols ...field.Expr) ISystemOauth2RefreshTokenDo
	Omit(cols ...field.Expr) ISystemOauth2RefreshTokenDo
	Join(table schema.Tabler, on ...field.Expr) ISystemOauth2RefreshTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemOauth2RefreshTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemOauth2RefreshTokenDo
	Group(cols ...field.Expr) ISystemOauth2RefreshTokenDo
	Having(conds ...gen.Condition) ISystemOauth2RefreshTokenDo
	Limit(limit int) ISystemOauth2RefreshTokenDo
	Offset(offset int) ISystemOauth2RefreshTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemOauth2RefreshTokenDo
	Unscoped() ISystemOauth2RefreshTokenDo
	Create(values ...*model.SystemOauth2RefreshToken) error
	CreateInBatches(values []*model.SystemOauth2RefreshToken, batchSize int) error
	Save(values ...*model.SystemOauth2RefreshToken) error
	First() (*model.SystemOauth2RefreshToken, error)
	Take() (*model.SystemOauth2RefreshToken, error)
	Last() (*model.SystemOauth2RefreshToken, error)
	Find() ([]*model.SystemOauth2RefreshToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemOauth2RefreshToken, err error)
	FindInBatches(result *[]*model.SystemOauth2RefreshToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemOauth2RefreshToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemOauth2RefreshTokenDo
	Assign(attrs ...field.AssignExpr) ISystemOauth2RefreshTokenDo
	Joins(fields ...field.RelationField) ISystemOauth2RefreshTokenDo
	Preload(fields ...field.RelationField) ISystemOauth2RefreshTokenDo
	FirstOrInit() (*model.SystemOauth2RefreshToken, error)
	FirstOrCreate() (*model.SystemOauth2RefreshToken, error)
	FindByPage(offset int, limit int) (result []*model.SystemOauth2RefreshToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemOauth2RefreshTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemOauth2RefreshTokenDo) Debug() ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Debug())
}

func (s systemOauth2RefreshTokenDo) WithContext(ctx context.Context) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemOauth2RefreshTokenDo) ReadDB() ISystemOauth2RefreshTokenDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemOauth2RefreshTokenDo) WriteDB() ISystemOauth2RefreshTokenDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemOauth2RefreshTokenDo) Session(config *gorm.Session) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemOauth2RefreshTokenDo) Clauses(conds ...clause.Expression) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemOauth2RefreshTokenDo) Returning(value interface{}, columns ...string) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemOauth2RefreshTokenDo) Not(conds ...gen.Condition) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemOauth2RefreshTokenDo) Or(conds ...gen.Condition) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemOauth2RefreshTokenDo) Select(conds ...field.Expr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemOauth2RefreshTokenDo) Where(conds ...gen.Condition) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemOauth2RefreshTokenDo) Order(conds ...field.Expr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemOauth2RefreshTokenDo) Distinct(cols ...field.Expr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemOauth2RefreshTokenDo) Omit(cols ...field.Expr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemOauth2RefreshTokenDo) Join(table schema.Tabler, on ...field.Expr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemOauth2RefreshTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemOauth2RefreshTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemOauth2RefreshTokenDo) Group(cols ...field.Expr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemOauth2RefreshTokenDo) Having(conds ...gen.Condition) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemOauth2RefreshTokenDo) Limit(limit int) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemOauth2RefreshTokenDo) Offset(offset int) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemOauth2RefreshTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemOauth2RefreshTokenDo) Unscoped() ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemOauth2RefreshTokenDo) Create(values ...*model.SystemOauth2RefreshToken) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemOauth2RefreshTokenDo) CreateInBatches(values []*model.SystemOauth2RefreshToken, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemOauth2RefreshTokenDo) Save(values ...*model.SystemOauth2RefreshToken) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemOauth2RefreshTokenDo) First() (*model.SystemOauth2RefreshToken, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2RefreshToken), nil
	}
}

func (s systemOauth2RefreshTokenDo) Take() (*model.SystemOauth2RefreshToken, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2RefreshToken), nil
	}
}

func (s systemOauth2RefreshTokenDo) Last() (*model.SystemOauth2RefreshToken, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2RefreshToken), nil
	}
}

func (s systemOauth2RefreshTokenDo) Find() ([]*model.SystemOauth2RefreshToken, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemOauth2RefreshToken), err
}

func (s systemOauth2RefreshTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemOauth2RefreshToken, err error) {
	buf := make([]*model.SystemOauth2RefreshToken, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemOauth2RefreshTokenDo) FindInBatches(result *[]*model.SystemOauth2RefreshToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemOauth2RefreshTokenDo) Attrs(attrs ...field.AssignExpr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemOauth2RefreshTokenDo) Assign(attrs ...field.AssignExpr) ISystemOauth2RefreshTokenDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemOauth2RefreshTokenDo) Joins(fields ...field.RelationField) ISystemOauth2RefreshTokenDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemOauth2RefreshTokenDo) Preload(fields ...field.RelationField) ISystemOauth2RefreshTokenDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemOauth2RefreshTokenDo) FirstOrInit() (*model.SystemOauth2RefreshToken, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2RefreshToken), nil
	}
}

func (s systemOauth2RefreshTokenDo) FirstOrCreate() (*model.SystemOauth2RefreshToken, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2RefreshToken), nil
	}
}

func (s systemOauth2RefreshTokenDo) FindByPage(offset int, limit int) (result []*model.SystemOauth2RefreshToken, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemOauth2RefreshTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemOauth2RefreshTokenDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemOauth2RefreshTokenDo) Delete(models ...*model.SystemOauth2RefreshToken) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemOauth2RefreshTokenDo) withDO(do gen.Dao) *systemOauth2RefreshTokenDo {
	s.DO = *do.(*gen.DO)
	return s
}
