// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newSystemPost(db *gorm.DB, opts ...gen.DOOption) systemPost {
	_systemPost := systemPost{}

	_systemPost.systemPostDo.UseDB(db, opts...)
	_systemPost.systemPostDo.UseModel(&model.SystemPost{})

	tableName := _systemPost.systemPostDo.TableName()
	_systemPost.ALL = field.NewAsterisk(tableName)
	_systemPost.ID = field.NewInt64(tableName, "id")
	_systemPost.Code = field.NewString(tableName, "code")
	_systemPost.Name = field.NewString(tableName, "name")
	_systemPost.Sort = field.NewInt32(tableName, "sort")
	_systemPost.Status = field.NewInt32(tableName, "status")
	_systemPost.Remark = field.NewString(tableName, "remark")
	_systemPost.Creator = field.NewString(tableName, "creator")
	_systemPost.CreateAt = field.NewTime(tableName, "create_at")
	_systemPost.Updater = field.NewString(tableName, "updater")
	_systemPost.UpdateAt = field.NewTime(tableName, "update_at")
	_systemPost.DeletedAt = field.NewField(tableName, "deleted_at")

	_systemPost.fillFieldMap()

	return _systemPost
}

// systemPost 岗位信息表
type systemPost struct {
	systemPostDo

	ALL       field.Asterisk
	ID        field.Int64  // 岗位ID
	Code      field.String // 岗位编码
	Name      field.String // 岗位名称
	Sort      field.Int32  // 显示顺序
	Status    field.Int32  // 状态（0正常 1停用）
	Remark    field.String // 备注
	Creator   field.String // 创建者
	CreateAt  field.Time   // 创建时间
	Updater   field.String // 更新者
	UpdateAt  field.Time   // 更新时间
	DeletedAt field.Field  // 删除字段

	fieldMap map[string]field.Expr
}

func (s systemPost) Table(newTableName string) *systemPost {
	s.systemPostDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemPost) As(alias string) *systemPost {
	s.systemPostDo.DO = *(s.systemPostDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemPost) updateTableName(table string) *systemPost {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Code = field.NewString(table, "code")
	s.Name = field.NewString(table, "name")
	s.Sort = field.NewInt32(table, "sort")
	s.Status = field.NewInt32(table, "status")
	s.Remark = field.NewString(table, "remark")
	s.Creator = field.NewString(table, "creator")
	s.CreateAt = field.NewTime(table, "create_at")
	s.Updater = field.NewString(table, "updater")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *systemPost) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemPost) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["code"] = s.Code
	s.fieldMap["name"] = s.Name
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["status"] = s.Status
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s systemPost) clone(db *gorm.DB) systemPost {
	s.systemPostDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemPost) replaceDB(db *gorm.DB) systemPost {
	s.systemPostDo.ReplaceDB(db)
	return s
}

type systemPostDo struct{ gen.DO }

type ISystemPostDo interface {
	gen.SubQuery
	Debug() ISystemPostDo
	WithContext(ctx context.Context) ISystemPostDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemPostDo
	WriteDB() ISystemPostDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemPostDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemPostDo
	Not(conds ...gen.Condition) ISystemPostDo
	Or(conds ...gen.Condition) ISystemPostDo
	Select(conds ...field.Expr) ISystemPostDo
	Where(conds ...gen.Condition) ISystemPostDo
	Order(conds ...field.Expr) ISystemPostDo
	Distinct(cols ...field.Expr) ISystemPostDo
	Omit(cols ...field.Expr) ISystemPostDo
	Join(table schema.Tabler, on ...field.Expr) ISystemPostDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemPostDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemPostDo
	Group(cols ...field.Expr) ISystemPostDo
	Having(conds ...gen.Condition) ISystemPostDo
	Limit(limit int) ISystemPostDo
	Offset(offset int) ISystemPostDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemPostDo
	Unscoped() ISystemPostDo
	Create(values ...*model.SystemPost) error
	CreateInBatches(values []*model.SystemPost, batchSize int) error
	Save(values ...*model.SystemPost) error
	First() (*model.SystemPost, error)
	Take() (*model.SystemPost, error)
	Last() (*model.SystemPost, error)
	Find() ([]*model.SystemPost, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemPost, err error)
	FindInBatches(result *[]*model.SystemPost, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemPost) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemPostDo
	Assign(attrs ...field.AssignExpr) ISystemPostDo
	Joins(fields ...field.RelationField) ISystemPostDo
	Preload(fields ...field.RelationField) ISystemPostDo
	FirstOrInit() (*model.SystemPost, error)
	FirstOrCreate() (*model.SystemPost, error)
	FindByPage(offset int, limit int) (result []*model.SystemPost, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemPostDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemPostDo) Debug() ISystemPostDo {
	return s.withDO(s.DO.Debug())
}

func (s systemPostDo) WithContext(ctx context.Context) ISystemPostDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemPostDo) ReadDB() ISystemPostDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemPostDo) WriteDB() ISystemPostDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemPostDo) Session(config *gorm.Session) ISystemPostDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemPostDo) Clauses(conds ...clause.Expression) ISystemPostDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemPostDo) Returning(value interface{}, columns ...string) ISystemPostDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemPostDo) Not(conds ...gen.Condition) ISystemPostDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemPostDo) Or(conds ...gen.Condition) ISystemPostDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemPostDo) Select(conds ...field.Expr) ISystemPostDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemPostDo) Where(conds ...gen.Condition) ISystemPostDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemPostDo) Order(conds ...field.Expr) ISystemPostDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemPostDo) Distinct(cols ...field.Expr) ISystemPostDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemPostDo) Omit(cols ...field.Expr) ISystemPostDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemPostDo) Join(table schema.Tabler, on ...field.Expr) ISystemPostDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemPostDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemPostDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemPostDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemPostDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemPostDo) Group(cols ...field.Expr) ISystemPostDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemPostDo) Having(conds ...gen.Condition) ISystemPostDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemPostDo) Limit(limit int) ISystemPostDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemPostDo) Offset(offset int) ISystemPostDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemPostDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemPostDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemPostDo) Unscoped() ISystemPostDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemPostDo) Create(values ...*model.SystemPost) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemPostDo) CreateInBatches(values []*model.SystemPost, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemPostDo) Save(values ...*model.SystemPost) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemPostDo) First() (*model.SystemPost, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPost), nil
	}
}

func (s systemPostDo) Take() (*model.SystemPost, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPost), nil
	}
}

func (s systemPostDo) Last() (*model.SystemPost, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPost), nil
	}
}

func (s systemPostDo) Find() ([]*model.SystemPost, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemPost), err
}

func (s systemPostDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemPost, err error) {
	buf := make([]*model.SystemPost, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemPostDo) FindInBatches(result *[]*model.SystemPost, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemPostDo) Attrs(attrs ...field.AssignExpr) ISystemPostDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemPostDo) Assign(attrs ...field.AssignExpr) ISystemPostDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemPostDo) Joins(fields ...field.RelationField) ISystemPostDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemPostDo) Preload(fields ...field.RelationField) ISystemPostDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemPostDo) FirstOrInit() (*model.SystemPost, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPost), nil
	}
}

func (s systemPostDo) FirstOrCreate() (*model.SystemPost, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemPost), nil
	}
}

func (s systemPostDo) FindByPage(offset int, limit int) (result []*model.SystemPost, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemPostDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemPostDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemPostDo) Delete(models ...*model.SystemPost) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemPostDo) withDO(do gen.Dao) *systemPostDo {
	s.DO = *do.(*gen.DO)
	return s
}
