// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newSystemOauth2AccessToken(db *gorm.DB, opts ...gen.DOOption) systemOauth2AccessToken {
	_systemOauth2AccessToken := systemOauth2AccessToken{}

	_systemOauth2AccessToken.systemOauth2AccessTokenDo.UseDB(db, opts...)
	_systemOauth2AccessToken.systemOauth2AccessTokenDo.UseModel(&model.SystemOauth2AccessToken{})

	tableName := _systemOauth2AccessToken.systemOauth2AccessTokenDo.TableName()
	_systemOauth2AccessToken.ALL = field.NewAsterisk(tableName)
	_systemOauth2AccessToken.ID = field.NewInt64(tableName, "id")
	_systemOauth2AccessToken.UserID = field.NewInt64(tableName, "user_id")
	_systemOauth2AccessToken.UserType = field.NewInt32(tableName, "user_type")
	_systemOauth2AccessToken.UserInfo = field.NewString(tableName, "user_info")
	_systemOauth2AccessToken.AccessToken = field.NewString(tableName, "access_token")
	_systemOauth2AccessToken.RefreshToken = field.NewString(tableName, "refresh_token")
	_systemOauth2AccessToken.ClientID = field.NewString(tableName, "client_id")
	_systemOauth2AccessToken.Scopes_ = field.NewString(tableName, "scopes")
	_systemOauth2AccessToken.ExpiresTime = field.NewTime(tableName, "expires_time")
	_systemOauth2AccessToken.Creator = field.NewString(tableName, "creator")
	_systemOauth2AccessToken.CreateAt = field.NewTime(tableName, "create_at")
	_systemOauth2AccessToken.Updater = field.NewString(tableName, "updater")
	_systemOauth2AccessToken.UpdateAt = field.NewTime(tableName, "update_at")
	_systemOauth2AccessToken.DeletedAt = field.NewField(tableName, "deleted_at")

	_systemOauth2AccessToken.fillFieldMap()

	return _systemOauth2AccessToken
}

// systemOauth2AccessToken OAuth2 访问令牌
type systemOauth2AccessToken struct {
	systemOauth2AccessTokenDo

	ALL          field.Asterisk
	ID           field.Int64  // 编号
	UserID       field.Int64  // 用户编号
	UserType     field.Int32  // 用户类型
	UserInfo     field.String // 用户信息
	AccessToken  field.String // 访问令牌
	RefreshToken field.String // 刷新令牌
	ClientID     field.String // 客户端编号
	Scopes_      field.String // 授权范围
	ExpiresTime  field.Time   // 过期时间
	Creator      field.String // 创建者
	CreateAt     field.Time   // 创建时间
	Updater      field.String // 更新者
	UpdateAt     field.Time   // 更新时间
	DeletedAt    field.Field  // 删除字段

	fieldMap map[string]field.Expr
}

func (s systemOauth2AccessToken) Table(newTableName string) *systemOauth2AccessToken {
	s.systemOauth2AccessTokenDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemOauth2AccessToken) As(alias string) *systemOauth2AccessToken {
	s.systemOauth2AccessTokenDo.DO = *(s.systemOauth2AccessTokenDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemOauth2AccessToken) updateTableName(table string) *systemOauth2AccessToken {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.UserID = field.NewInt64(table, "user_id")
	s.UserType = field.NewInt32(table, "user_type")
	s.UserInfo = field.NewString(table, "user_info")
	s.AccessToken = field.NewString(table, "access_token")
	s.RefreshToken = field.NewString(table, "refresh_token")
	s.ClientID = field.NewString(table, "client_id")
	s.Scopes_ = field.NewString(table, "scopes")
	s.ExpiresTime = field.NewTime(table, "expires_time")
	s.Creator = field.NewString(table, "creator")
	s.CreateAt = field.NewTime(table, "create_at")
	s.Updater = field.NewString(table, "updater")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *systemOauth2AccessToken) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemOauth2AccessToken) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 14)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["user_type"] = s.UserType
	s.fieldMap["user_info"] = s.UserInfo
	s.fieldMap["access_token"] = s.AccessToken
	s.fieldMap["refresh_token"] = s.RefreshToken
	s.fieldMap["client_id"] = s.ClientID
	s.fieldMap["scopes"] = s.Scopes_
	s.fieldMap["expires_time"] = s.ExpiresTime
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s systemOauth2AccessToken) clone(db *gorm.DB) systemOauth2AccessToken {
	s.systemOauth2AccessTokenDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemOauth2AccessToken) replaceDB(db *gorm.DB) systemOauth2AccessToken {
	s.systemOauth2AccessTokenDo.ReplaceDB(db)
	return s
}

type systemOauth2AccessTokenDo struct{ gen.DO }

type ISystemOauth2AccessTokenDo interface {
	gen.SubQuery
	Debug() ISystemOauth2AccessTokenDo
	WithContext(ctx context.Context) ISystemOauth2AccessTokenDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemOauth2AccessTokenDo
	WriteDB() ISystemOauth2AccessTokenDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemOauth2AccessTokenDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemOauth2AccessTokenDo
	Not(conds ...gen.Condition) ISystemOauth2AccessTokenDo
	Or(conds ...gen.Condition) ISystemOauth2AccessTokenDo
	Select(conds ...field.Expr) ISystemOauth2AccessTokenDo
	Where(conds ...gen.Condition) ISystemOauth2AccessTokenDo
	Order(conds ...field.Expr) ISystemOauth2AccessTokenDo
	Distinct(cols ...field.Expr) ISystemOauth2AccessTokenDo
	Omit(cols ...field.Expr) ISystemOauth2AccessTokenDo
	Join(table schema.Tabler, on ...field.Expr) ISystemOauth2AccessTokenDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemOauth2AccessTokenDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemOauth2AccessTokenDo
	Group(cols ...field.Expr) ISystemOauth2AccessTokenDo
	Having(conds ...gen.Condition) ISystemOauth2AccessTokenDo
	Limit(limit int) ISystemOauth2AccessTokenDo
	Offset(offset int) ISystemOauth2AccessTokenDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemOauth2AccessTokenDo
	Unscoped() ISystemOauth2AccessTokenDo
	Create(values ...*model.SystemOauth2AccessToken) error
	CreateInBatches(values []*model.SystemOauth2AccessToken, batchSize int) error
	Save(values ...*model.SystemOauth2AccessToken) error
	First() (*model.SystemOauth2AccessToken, error)
	Take() (*model.SystemOauth2AccessToken, error)
	Last() (*model.SystemOauth2AccessToken, error)
	Find() ([]*model.SystemOauth2AccessToken, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemOauth2AccessToken, err error)
	FindInBatches(result *[]*model.SystemOauth2AccessToken, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemOauth2AccessToken) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemOauth2AccessTokenDo
	Assign(attrs ...field.AssignExpr) ISystemOauth2AccessTokenDo
	Joins(fields ...field.RelationField) ISystemOauth2AccessTokenDo
	Preload(fields ...field.RelationField) ISystemOauth2AccessTokenDo
	FirstOrInit() (*model.SystemOauth2AccessToken, error)
	FirstOrCreate() (*model.SystemOauth2AccessToken, error)
	FindByPage(offset int, limit int) (result []*model.SystemOauth2AccessToken, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemOauth2AccessTokenDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemOauth2AccessTokenDo) Debug() ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Debug())
}

func (s systemOauth2AccessTokenDo) WithContext(ctx context.Context) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemOauth2AccessTokenDo) ReadDB() ISystemOauth2AccessTokenDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemOauth2AccessTokenDo) WriteDB() ISystemOauth2AccessTokenDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemOauth2AccessTokenDo) Session(config *gorm.Session) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemOauth2AccessTokenDo) Clauses(conds ...clause.Expression) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemOauth2AccessTokenDo) Returning(value interface{}, columns ...string) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemOauth2AccessTokenDo) Not(conds ...gen.Condition) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemOauth2AccessTokenDo) Or(conds ...gen.Condition) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemOauth2AccessTokenDo) Select(conds ...field.Expr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemOauth2AccessTokenDo) Where(conds ...gen.Condition) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemOauth2AccessTokenDo) Order(conds ...field.Expr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemOauth2AccessTokenDo) Distinct(cols ...field.Expr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemOauth2AccessTokenDo) Omit(cols ...field.Expr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemOauth2AccessTokenDo) Join(table schema.Tabler, on ...field.Expr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemOauth2AccessTokenDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemOauth2AccessTokenDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemOauth2AccessTokenDo) Group(cols ...field.Expr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemOauth2AccessTokenDo) Having(conds ...gen.Condition) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemOauth2AccessTokenDo) Limit(limit int) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemOauth2AccessTokenDo) Offset(offset int) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemOauth2AccessTokenDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemOauth2AccessTokenDo) Unscoped() ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemOauth2AccessTokenDo) Create(values ...*model.SystemOauth2AccessToken) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemOauth2AccessTokenDo) CreateInBatches(values []*model.SystemOauth2AccessToken, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemOauth2AccessTokenDo) Save(values ...*model.SystemOauth2AccessToken) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemOauth2AccessTokenDo) First() (*model.SystemOauth2AccessToken, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2AccessToken), nil
	}
}

func (s systemOauth2AccessTokenDo) Take() (*model.SystemOauth2AccessToken, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2AccessToken), nil
	}
}

func (s systemOauth2AccessTokenDo) Last() (*model.SystemOauth2AccessToken, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2AccessToken), nil
	}
}

func (s systemOauth2AccessTokenDo) Find() ([]*model.SystemOauth2AccessToken, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemOauth2AccessToken), err
}

func (s systemOauth2AccessTokenDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemOauth2AccessToken, err error) {
	buf := make([]*model.SystemOauth2AccessToken, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemOauth2AccessTokenDo) FindInBatches(result *[]*model.SystemOauth2AccessToken, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemOauth2AccessTokenDo) Attrs(attrs ...field.AssignExpr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemOauth2AccessTokenDo) Assign(attrs ...field.AssignExpr) ISystemOauth2AccessTokenDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemOauth2AccessTokenDo) Joins(fields ...field.RelationField) ISystemOauth2AccessTokenDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemOauth2AccessTokenDo) Preload(fields ...field.RelationField) ISystemOauth2AccessTokenDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemOauth2AccessTokenDo) FirstOrInit() (*model.SystemOauth2AccessToken, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2AccessToken), nil
	}
}

func (s systemOauth2AccessTokenDo) FirstOrCreate() (*model.SystemOauth2AccessToken, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemOauth2AccessToken), nil
	}
}

func (s systemOauth2AccessTokenDo) FindByPage(offset int, limit int) (result []*model.SystemOauth2AccessToken, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemOauth2AccessTokenDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemOauth2AccessTokenDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemOauth2AccessTokenDo) Delete(models ...*model.SystemOauth2AccessToken) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemOauth2AccessTokenDo) withDO(do gen.Dao) *systemOauth2AccessTokenDo {
	s.DO = *do.(*gen.DO)
	return s
}
