// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"k8s-platform-go/internal/dal/model"
)

func newSystemDept(db *gorm.DB, opts ...gen.DOOption) systemDept {
	_systemDept := systemDept{}

	_systemDept.systemDeptDo.UseDB(db, opts...)
	_systemDept.systemDeptDo.UseModel(&model.SystemDept{})

	tableName := _systemDept.systemDeptDo.TableName()
	_systemDept.ALL = field.NewAsterisk(tableName)
	_systemDept.ID = field.NewInt64(tableName, "id")
	_systemDept.Name = field.NewString(tableName, "name")
	_systemDept.ParentID = field.NewInt64(tableName, "parent_id")
	_systemDept.Sort = field.NewInt32(tableName, "sort")
	_systemDept.LeaderUserID = field.NewInt64(tableName, "leader_user_id")
	_systemDept.Phone = field.NewString(tableName, "phone")
	_systemDept.Email = field.NewString(tableName, "email")
	_systemDept.Status = field.NewInt32(tableName, "status")
	_systemDept.Creator = field.NewString(tableName, "creator")
	_systemDept.CreateAt = field.NewTime(tableName, "create_at")
	_systemDept.Updater = field.NewString(tableName, "updater")
	_systemDept.UpdateAt = field.NewTime(tableName, "update_at")
	_systemDept.DeletedAt = field.NewField(tableName, "deleted_at")

	_systemDept.fillFieldMap()

	return _systemDept
}

// systemDept 部门表
type systemDept struct {
	systemDeptDo

	ALL          field.Asterisk
	ID           field.Int64  // 部门id
	Name         field.String // 部门名称
	ParentID     field.Int64  // 父部门id
	Sort         field.Int32  // 显示顺序
	LeaderUserID field.Int64  // 负责人
	Phone        field.String // 联系电话
	Email        field.String // 邮箱
	Status       field.Int32  // 部门状态（0正常 1停用）
	Creator      field.String // 创建者
	CreateAt     field.Time   // 创建时间
	Updater      field.String // 更新者
	UpdateAt     field.Time   // 更新时间
	DeletedAt    field.Field  // 删除字段

	fieldMap map[string]field.Expr
}

func (s systemDept) Table(newTableName string) *systemDept {
	s.systemDeptDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemDept) As(alias string) *systemDept {
	s.systemDeptDo.DO = *(s.systemDeptDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemDept) updateTableName(table string) *systemDept {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.ParentID = field.NewInt64(table, "parent_id")
	s.Sort = field.NewInt32(table, "sort")
	s.LeaderUserID = field.NewInt64(table, "leader_user_id")
	s.Phone = field.NewString(table, "phone")
	s.Email = field.NewString(table, "email")
	s.Status = field.NewInt32(table, "status")
	s.Creator = field.NewString(table, "creator")
	s.CreateAt = field.NewTime(table, "create_at")
	s.Updater = field.NewString(table, "updater")
	s.UpdateAt = field.NewTime(table, "update_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *systemDept) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemDept) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["leader_user_id"] = s.LeaderUserID
	s.fieldMap["phone"] = s.Phone
	s.fieldMap["email"] = s.Email
	s.fieldMap["status"] = s.Status
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["create_at"] = s.CreateAt
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["update_at"] = s.UpdateAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s systemDept) clone(db *gorm.DB) systemDept {
	s.systemDeptDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemDept) replaceDB(db *gorm.DB) systemDept {
	s.systemDeptDo.ReplaceDB(db)
	return s
}

type systemDeptDo struct{ gen.DO }

type ISystemDeptDo interface {
	gen.SubQuery
	Debug() ISystemDeptDo
	WithContext(ctx context.Context) ISystemDeptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISystemDeptDo
	WriteDB() ISystemDeptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISystemDeptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISystemDeptDo
	Not(conds ...gen.Condition) ISystemDeptDo
	Or(conds ...gen.Condition) ISystemDeptDo
	Select(conds ...field.Expr) ISystemDeptDo
	Where(conds ...gen.Condition) ISystemDeptDo
	Order(conds ...field.Expr) ISystemDeptDo
	Distinct(cols ...field.Expr) ISystemDeptDo
	Omit(cols ...field.Expr) ISystemDeptDo
	Join(table schema.Tabler, on ...field.Expr) ISystemDeptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISystemDeptDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISystemDeptDo
	Group(cols ...field.Expr) ISystemDeptDo
	Having(conds ...gen.Condition) ISystemDeptDo
	Limit(limit int) ISystemDeptDo
	Offset(offset int) ISystemDeptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemDeptDo
	Unscoped() ISystemDeptDo
	Create(values ...*model.SystemDept) error
	CreateInBatches(values []*model.SystemDept, batchSize int) error
	Save(values ...*model.SystemDept) error
	First() (*model.SystemDept, error)
	Take() (*model.SystemDept, error)
	Last() (*model.SystemDept, error)
	Find() ([]*model.SystemDept, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDept, err error)
	FindInBatches(result *[]*model.SystemDept, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SystemDept) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISystemDeptDo
	Assign(attrs ...field.AssignExpr) ISystemDeptDo
	Joins(fields ...field.RelationField) ISystemDeptDo
	Preload(fields ...field.RelationField) ISystemDeptDo
	FirstOrInit() (*model.SystemDept, error)
	FirstOrCreate() (*model.SystemDept, error)
	FindByPage(offset int, limit int) (result []*model.SystemDept, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISystemDeptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s systemDeptDo) Debug() ISystemDeptDo {
	return s.withDO(s.DO.Debug())
}

func (s systemDeptDo) WithContext(ctx context.Context) ISystemDeptDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemDeptDo) ReadDB() ISystemDeptDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemDeptDo) WriteDB() ISystemDeptDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemDeptDo) Session(config *gorm.Session) ISystemDeptDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemDeptDo) Clauses(conds ...clause.Expression) ISystemDeptDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemDeptDo) Returning(value interface{}, columns ...string) ISystemDeptDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemDeptDo) Not(conds ...gen.Condition) ISystemDeptDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemDeptDo) Or(conds ...gen.Condition) ISystemDeptDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemDeptDo) Select(conds ...field.Expr) ISystemDeptDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemDeptDo) Where(conds ...gen.Condition) ISystemDeptDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemDeptDo) Order(conds ...field.Expr) ISystemDeptDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemDeptDo) Distinct(cols ...field.Expr) ISystemDeptDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemDeptDo) Omit(cols ...field.Expr) ISystemDeptDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemDeptDo) Join(table schema.Tabler, on ...field.Expr) ISystemDeptDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemDeptDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISystemDeptDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemDeptDo) RightJoin(table schema.Tabler, on ...field.Expr) ISystemDeptDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemDeptDo) Group(cols ...field.Expr) ISystemDeptDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemDeptDo) Having(conds ...gen.Condition) ISystemDeptDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemDeptDo) Limit(limit int) ISystemDeptDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemDeptDo) Offset(offset int) ISystemDeptDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemDeptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISystemDeptDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemDeptDo) Unscoped() ISystemDeptDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemDeptDo) Create(values ...*model.SystemDept) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemDeptDo) CreateInBatches(values []*model.SystemDept, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemDeptDo) Save(values ...*model.SystemDept) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemDeptDo) First() (*model.SystemDept, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDept), nil
	}
}

func (s systemDeptDo) Take() (*model.SystemDept, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDept), nil
	}
}

func (s systemDeptDo) Last() (*model.SystemDept, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDept), nil
	}
}

func (s systemDeptDo) Find() ([]*model.SystemDept, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemDept), err
}

func (s systemDeptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDept, err error) {
	buf := make([]*model.SystemDept, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemDeptDo) FindInBatches(result *[]*model.SystemDept, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemDeptDo) Attrs(attrs ...field.AssignExpr) ISystemDeptDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemDeptDo) Assign(attrs ...field.AssignExpr) ISystemDeptDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemDeptDo) Joins(fields ...field.RelationField) ISystemDeptDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemDeptDo) Preload(fields ...field.RelationField) ISystemDeptDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemDeptDo) FirstOrInit() (*model.SystemDept, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDept), nil
	}
}

func (s systemDeptDo) FirstOrCreate() (*model.SystemDept, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDept), nil
	}
}

func (s systemDeptDo) FindByPage(offset int, limit int) (result []*model.SystemDept, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemDeptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemDeptDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemDeptDo) Delete(models ...*model.SystemDept) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemDeptDo) withDO(do gen.Dao) *systemDeptDo {
	s.DO = *do.(*gen.DO)
	return s
}
