// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJobScheduledTask = "job_scheduled_task"

// JobScheduledTask 定时任务
type JobScheduledTask struct {
	ID               uint32         `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`             // 主键id
	Name             string         `gorm:"column:name;type:varchar(50);not null;comment:任务名称" json:"name"`                                   // 任务名称
	PlanID           uint32         `gorm:"column:plan_id;type:int(10) unsigned;not null;comment:计划id" json:"planId"`                         // 计划id
	Strategy         string         `gorm:"column:strategy;type:varchar(50);not null;comment:执行策略" json:"strategy"`                           // 执行策略
	LeatestStatus    string         `gorm:"column:leatest_status;type:varchar(20);not null;comment:最新执行结果" json:"leatestStatus"`              // 最新执行结果
	SycleSuccessRate string         `gorm:"column:sycle_success_rate;type:varchar(20);not null;comment:周期成功率" json:"sycleSuccessRate"`        // 周期成功率
	Status           uint32         `gorm:"column:status;type:tinyint(3) unsigned;not null;comment:是否开启" json:"status"`                       // 是否开启
	CreatedAt        time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deletedAt"`                                    // 删除时间
}

// TableName JobScheduledTask's table name
func (*JobScheduledTask) TableName() string {
	return TableNameJobScheduledTask
}
