// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJobPlan = "job_plan"

// JobPlan 执行计划
type JobPlan struct {
	ID          uint32         `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`             // 主键id
	Name        string         `gorm:"column:name;type:varchar(50);not null;comment:任务名称" json:"name"`                                   // 任务名称
	GlobalVars  string         `gorm:"column:global_vars;type:varchar(255);not null;comment:全局变量" json:"globalVars"`                     // 全局变量
	HostIds     string         `gorm:"column:host_ids;type:varchar(255);not null;comment:主机列表" json:"hostIds"`                           // 主机列表
	HostGroupID *uint32        `gorm:"column:host_group_id;type:int(10) unsigned;comment:主机组id" json:"hostGroupId"`                      // 主机组id
	Remark      *string        `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                                         // 备注
	CreatedAt   time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deletedAt"`                                    // 删除时间
}

// TableName JobPlan's table name
func (*JobPlan) TableName() string {
	return TableNameJobPlan
}
