// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJobPlanLog = "job_plan_log"

// JobPlanLog mapped from table <job_plan_log>
type JobPlanLog struct {
	ID         int32          `gorm:"column:id;type:int(11);primaryKey;comment:主键id" json:"id"`                                         // 主键id
	PlanID     int32          `gorm:"column:plan_id;type:int(11);not null;comment:计划id" json:"planId"`                                  // 计划id
	HostID     uint32         `gorm:"column:host_id;type:int(10) unsigned;not null;comment:主机id" json:"hostId"`                         // 主机id
	Method     string         `gorm:"column:method;type:varchar(50);not null;comment:执行方式" json:"method"`                               // 执行方式
	Type       string         `gorm:"column:type;type:varchar(50);not null;comment:任务类型" json:"type"`                                   // 任务类型
	Status     bool           `gorm:"column:status;type:tinyint(1) unsigned;not null;comment:执行状态" json:"status"`                       // 执行状态
	TotalTime  string         `gorm:"column:total_time;type:varchar(25);not null;comment:总耗时" json:"totalTime"`                         // 总耗时
	ReturnCode int32          `gorm:"column:return_code;type:int(11);not null;comment:退出码" json:"returnCode"`                           // 退出码
	Output     *string        `gorm:"column:output;type:varchar(1024);comment:日志" json:"output"`                                        // 日志
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deletedAt"`                                    // 删除时间
}

// TableName JobPlanLog's table name
func (*JobPlanLog) TableName() string {
	return TableNameJobPlanLog
}
