// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJobScript = "job_script"

// JobScript 脚本
type JobScript struct {
	ID         uint32         `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true;comment:主键id" json:"id"`             // 主键id
	Name       string         `gorm:"column:name;type:varchar(255);not null;comment:脚本名称" json:"name"`                                  // 脚本名称
	Type       string         `gorm:"column:type;type:varchar(20);not null;comment:类型" json:"type"`                                     // 类型
	Category   string         `gorm:"column:category;type:varchar(30);not null;comment:类别，默认是default" json:"category"`                  // 类别，默认是default
	Content    string         `gorm:"column:content;type:varchar(500);not null;comment:脚本内容" json:"content"`                            // 脚本内容
	Parameters string         `gorm:"column:parameters;type:varchar(255);not null;comment:脚本参数" json:"parameters"`                      // 脚本参数
	Timeout    uint32         `gorm:"column:timeout;type:int(10) unsigned;not null;comment:超时时间" json:"timeout"`                        // 超时时间
	WorkDir    *string        `gorm:"column:work_dir;type:varchar(255);comment:工作路径" json:"workDir"`                                    // 工作路径
	Env        *string        `gorm:"column:env;type:varchar(255);comment:环境变量" json:"env"`                                             // 环境变量
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deletedAt"`                                    // 删除时间
}

// TableName JobScript's table name
func (*JobScript) TableName() string {
	return TableNameJobScript
}
