// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemDictDatum = "system_dict_data"

// SystemDictDatum 字典数据表
type SystemDictDatum struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:字典编码" json:"id"`                      // 字典编码
	Sort      int32          `gorm:"column:sort;type:int;not null;comment:字典排序" json:"sort"`                                          // 字典排序
	Label     string         `gorm:"column:label;type:varchar(100);not null;comment:字典标签" json:"label"`                               // 字典标签
	Value     string         `gorm:"column:value;type:varchar(100);not null;comment:字典键值" json:"value"`                               // 字典键值
	DictType  string         `gorm:"column:dict_type;type:varchar(100);not null;comment:字典类型" json:"dict_type"`                       // 字典类型
	Status    int32          `gorm:"column:status;type:tinyint;not null;comment:状态（0正常 1停用）" json:"status"`                           // 状态（0正常 1停用）
	ColorType *string        `gorm:"column:color_type;type:varchar(100);comment:颜色类型" json:"color_type"`                              // 颜色类型
	CSSClass  *string        `gorm:"column:css_class;type:varchar(100);comment:css 样式" json:"css_class"`                              // css 样式
	Remark    *string        `gorm:"column:remark;type:varchar(500);comment:备注" json:"remark"`                                        // 备注
	Creator   *string        `gorm:"column:creator;type:varchar(64);comment:创建者" json:"creator"`                                      // 创建者
	CreateAt  time.Time      `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	Updater   *string        `gorm:"column:updater;type:varchar(64);comment:更新者" json:"updater"`                                      // 更新者
	UpdateAt  time.Time      `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除字段" json:"deleted_at"`                                  // 删除字段
}

// TableName SystemDictDatum's table name
func (*SystemDictDatum) TableName() string {
	return TableNameSystemDictDatum
}
