// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemOperateLog = "system_operate_log"

// SystemOperateLog 操作日志记录 V2 版本
type SystemOperateLog struct {
	ID            int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:日志主键" json:"id"`                      // 日志主键
	TraceID       string         `gorm:"column:trace_id;type:varchar(64);not null;comment:链路追踪编号" json:"trace_id"`                        // 链路追踪编号
	UserID        int64          `gorm:"column:user_id;type:bigint;not null;comment:用户编号" json:"user_id"`                                 // 用户编号
	UserType      int32          `gorm:"column:user_type;type:tinyint;not null;comment:用户类型" json:"user_type"`                            // 用户类型
	Type          string         `gorm:"column:type;type:varchar(50);not null;comment:操作模块类型" json:"type"`                                // 操作模块类型
	SubType       string         `gorm:"column:sub_type;type:varchar(50);not null;comment:操作名" json:"sub_type"`                           // 操作名
	BizID         int64          `gorm:"column:biz_id;type:bigint;not null;comment:操作数据模块编号" json:"biz_id"`                               // 操作数据模块编号
	Action        string         `gorm:"column:action;type:varchar(2000);not null;comment:操作内容" json:"action"`                            // 操作内容
	Success       []uint8        `gorm:"column:success;type:bit(1);not null;default:b'1';comment:操作结果" json:"success"`                    // 操作结果
	Extra         string         `gorm:"column:extra;type:varchar(2000);not null;comment:拓展字段" json:"extra"`                              // 拓展字段
	RequestMethod *string        `gorm:"column:request_method;type:varchar(16);comment:请求方法名" json:"request_method"`                      // 请求方法名
	RequestURL    *string        `gorm:"column:request_url;type:varchar(255);comment:请求地址" json:"request_url"`                            // 请求地址
	UserIP        *string        `gorm:"column:user_ip;type:varchar(50);comment:用户 IP" json:"user_ip"`                                    // 用户 IP
	UserAgent     *string        `gorm:"column:user_agent;type:varchar(512);comment:浏览器 UA" json:"user_agent"`                            // 浏览器 UA
	Creator       *string        `gorm:"column:creator;type:varchar(64);comment:创建者" json:"creator"`                                      // 创建者
	CreateAt      time.Time      `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	Updater       *string        `gorm:"column:updater;type:varchar(64);comment:更新者" json:"updater"`                                      // 更新者
	UpdateAt      time.Time      `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除字段" json:"deleted_at"`                                  // 删除字段
}

// TableName SystemOperateLog's table name
func (*SystemOperateLog) TableName() string {
	return TableNameSystemOperateLog
}
