// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemUser = "system_users"

// SystemUser 用户信息表
type SystemUser struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                     // 用户ID
	Username  string         `gorm:"column:username;type:varchar(30);not null;comment:用户账号" json:"username"`                         // 用户账号
	Password  string         `gorm:"column:password;type:varchar(100);not null;comment:密码" json:"password"`                          // 密码
	Nickname  string         `gorm:"column:nickname;type:varchar(30);not null;comment:用户昵称" json:"nickname"`                         // 用户昵称
	Remark    *string        `gorm:"column:remark;type:varchar(500);comment:备注" json:"remark"`                                       // 备注
	DeptID    *int64         `gorm:"column:dept_id;type:bigint;comment:部门ID" json:"deptId"`                                          // 部门ID
	PostIds   *string        `gorm:"column:post_ids;type:varchar(255);comment:岗位编号数组" json:"postIds"`                                // 岗位编号数组
	Email     *string        `gorm:"column:email;type:varchar(50);comment:用户邮箱" json:"email"`                                        // 用户邮箱
	Mobile    *string        `gorm:"column:mobile;type:varchar(11);comment:手机号码" json:"mobile"`                                      // 手机号码
	Sex       *int32         `gorm:"column:sex;type:tinyint;comment:用户性别" json:"sex"`                                                // 用户性别
	Avatar    *string        `gorm:"column:avatar;type:varchar(512);comment:头像地址" json:"avatar"`                                     // 头像地址
	Status    int32          `gorm:"column:status;type:tinyint;not null;comment:帐号状态（0正常 1停用）" json:"status"`                        // 帐号状态（0正常 1停用）
	LoginIP   *string        `gorm:"column:login_ip;type:varchar(50);comment:最后登录IP" json:"loginIp"`                                 // 最后登录IP
	LoginDate *time.Time     `gorm:"column:login_date;type:datetime;comment:最后登录时间" json:"loginDate"`                                // 最后登录时间
	Creator   *string        `gorm:"column:creator;type:varchar(64);comment:创建者" json:"creator"`                                     // 创建者
	CreateAt  time.Time      `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createAt"` // 创建时间
	Updater   *string        `gorm:"column:updater;type:varchar(64);comment:更新者" json:"updater"`                                     // 更新者
	UpdateAt  time.Time      `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateAt"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deletedAt"`                                  // 删除时间
}

// TableName SystemUser's table name
func (*SystemUser) TableName() string {
	return TableNameSystemUser
}
