// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemOauth2RefreshToken = "system_oauth2_refresh_token"

// SystemOauth2RefreshToken OAuth2 刷新令牌
type SystemOauth2RefreshToken struct {
	ID           int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:编号" json:"id"`                    // 编号
	UserID       int64          `gorm:"column:user_id;type:bigint(20);not null;comment:用户编号" json:"user_id"`                             // 用户编号
	RefreshToken string         `gorm:"column:refresh_token;type:varchar(32);not null;comment:刷新令牌" json:"refresh_token"`                // 刷新令牌
	UserType     int32          `gorm:"column:user_type;type:tinyint(4);not null;comment:用户类型" json:"user_type"`                         // 用户类型
	ClientID     string         `gorm:"column:client_id;type:varchar(255);not null;comment:客户端编号" json:"client_id"`                      // 客户端编号
	Scopes_      *string        `gorm:"column:scopes;type:varchar(255);comment:授权范围" json:"scopes"`                                      // 授权范围
	ExpiresTime  time.Time      `gorm:"column:expires_time;type:datetime;not null;comment:过期时间" json:"expires_time"`                     // 过期时间
	Creator      *string        `gorm:"column:creator;type:varchar(64);comment:创建者" json:"creator"`                                      // 创建者
	CreateAt     time.Time      `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	Updater      *string        `gorm:"column:updater;type:varchar(64);comment:更新者" json:"updater"`                                      // 更新者
	UpdateAt     time.Time      `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"` // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除字段" json:"deleted_at"`                                  // 删除字段
}

// TableName SystemOauth2RefreshToken's table name
func (*SystemOauth2RefreshToken) TableName() string {
	return TableNameSystemOauth2RefreshToken
}
