// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemUserPost = "system_user_post"

// SystemUserPost 用户岗位表
type SystemUserPost struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:id" json:"id"`                    // id
	UserID    int64          `gorm:"column:user_id;type:bigint(20);not null;comment:用户ID" json:"user_id"`                             // 用户ID
	PostID    int64          `gorm:"column:post_id;type:bigint(20);not null;comment:岗位ID" json:"post_id"`                             // 岗位ID
	Creator   *string        `gorm:"column:creator;type:varchar(64);comment:创建者" json:"creator"`                                      // 创建者
	CreateAt  time.Time      `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	Updater   *string        `gorm:"column:updater;type:varchar(64);comment:更新者" json:"updater"`                                      // 更新者
	UpdateAt  time.Time      `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除字段" json:"deleted_at"`                                  // 删除字段
}

// TableName SystemUserPost's table name
func (*SystemUserPost) TableName() string {
	return TableNameSystemUserPost
}
