// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemLoginLog = "system_login_log"

// SystemLoginLog 系统访问记录
type SystemLoginLog struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:访问ID" json:"id"`                     // 访问ID
	LogType   int64          `gorm:"column:log_type;type:bigint;not null;comment:日志类型" json:"logType"`                               // 日志类型
	TraceID   string         `gorm:"column:trace_id;type:varchar(64);not null;comment:链路追踪编号" json:"traceId"`                        // 链路追踪编号
	UserID    int64          `gorm:"column:user_id;type:bigint;not null;comment:用户编号" json:"userId"`                                 // 用户编号
	UserType  int32          `gorm:"column:user_type;type:tinyint;not null;comment:用户类型" json:"userType"`                            // 用户类型
	Username  string         `gorm:"column:username;type:varchar(50);not null;comment:用户账号" json:"username"`                         // 用户账号
	Result    int32          `gorm:"column:result;type:tinyint;not null;comment:登陆结果" json:"result"`                                 // 登陆结果
	UserIP    string         `gorm:"column:user_ip;type:varchar(50);not null;comment:用户 IP" json:"userIp"`                           // 用户 IP
	UserAgent string         `gorm:"column:user_agent;type:varchar(512);not null;comment:浏览器 UA" json:"userAgent"`                   // 浏览器 UA
	Creator   *string        `gorm:"column:creator;type:varchar(64);comment:创建者" json:"creator"`                                     // 创建者
	CreateAt  time.Time      `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createAt"` // 创建时间
	Updater   *string        `gorm:"column:updater;type:varchar(64);comment:更新者" json:"updater"`                                     // 更新者
	UpdateAt  time.Time      `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateAt"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除字段" json:"deletedAt"`                                  // 删除字段
}

// TableName SystemLoginLog's table name
func (*SystemLoginLog) TableName() string {
	return TableNameSystemLoginLog
}
