// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemMenu = "system_menu"

// SystemMenu 菜单权限表
type SystemMenu struct {
	ID            int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:菜单ID" json:"id"`                  // 菜单ID
	Name          string         `gorm:"column:name;type:varchar(50);not null;comment:菜单名称" json:"name"`                                  // 菜单名称
	Permission    string         `gorm:"column:permission;type:varchar(100);not null;comment:权限标识" json:"permission"`                     // 权限标识
	Type          int32          `gorm:"column:type;type:tinyint(4);not null;comment:菜单类型" json:"type"`                                   // 菜单类型
	Sort          int32          `gorm:"column:sort;type:int(11);not null;comment:显示顺序" json:"sort"`                                      // 显示顺序
	ParentID      int64          `gorm:"column:parent_id;type:bigint(20);not null;comment:父菜单ID" json:"parent_id"`                        // 父菜单ID
	Path          *string        `gorm:"column:path;type:varchar(200);comment:路由地址" json:"path"`                                          // 路由地址
	Icon          *string        `gorm:"column:icon;type:varchar(100);default:#;comment:菜单图标" json:"icon"`                                // 菜单图标
	Component     *string        `gorm:"column:component;type:varchar(255);comment:组件路径" json:"component"`                                // 组件路径
	ComponentName *string        `gorm:"column:component_name;type:varchar(255);comment:组件名" json:"component_name"`                       // 组件名
	Status        int32          `gorm:"column:status;type:tinyint(4);not null;comment:菜单状态" json:"status"`                               // 菜单状态
	Visible       []uint8        `gorm:"column:visible;type:bit(1);not null;default:b'1';comment:是否可见" json:"visible"`                    // 是否可见
	KeepAlive     []uint8        `gorm:"column:keep_alive;type:bit(1);not null;default:b'1';comment:是否缓存" json:"keep_alive"`              // 是否缓存
	AlwaysShow    []uint8        `gorm:"column:always_show;type:bit(1);not null;default:b'1';comment:是否总是显示" json:"always_show"`          // 是否总是显示
	Creator       *string        `gorm:"column:creator;type:varchar(64);comment:创建者" json:"creator"`                                      // 创建者
	CreateAt      time.Time      `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	Updater       *string        `gorm:"column:updater;type:varchar(64);comment:更新者" json:"updater"`                                      // 更新者
	UpdateAt      time.Time      `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除字段" json:"deleted_at"`                                  // 删除字段
}

// TableName SystemMenu's table name
func (*SystemMenu) TableName() string {
	return TableNameSystemMenu
}
