// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSystemRoleMenu = "system_role_menu"

// SystemRoleMenu 角色和菜单关联表
type SystemRoleMenu struct {
	ID        int64          `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:自增编号" json:"id"`                  // 自增编号
	RoleID    int64          `gorm:"column:role_id;type:bigint(20);not null;comment:角色ID" json:"role_id"`                             // 角色ID
	MenuID    int64          `gorm:"column:menu_id;type:bigint(20);not null;comment:菜单ID" json:"menu_id"`                             // 菜单ID
	Creator   *string        `gorm:"column:creator;type:varchar(64);comment:创建者" json:"creator"`                                      // 创建者
	CreateAt  time.Time      `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	Updater   *string        `gorm:"column:updater;type:varchar(64);comment:更新者" json:"updater"`                                      // 更新者
	UpdateAt  time.Time      `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除字段" json:"deleted_at"`                                  // 删除字段
}

// TableName SystemRoleMenu's table name
func (*SystemRoleMenu) TableName() string {
	return TableNameSystemRoleMenu
}
