server:
  port: "8081"
  debug: true

database:
  dsn: "root:peppa-pig@tcp(39.103.56.192:8002)/k8s?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  host: 39.103.56.192
  port: 8001
  password:
  db: 0

jwt:
  secret: "n02y2Zqf4eL0hZ4xjQH9w1zDk1w5FqMnc9R+N8T1v2E="
  expire-time: 3600 # 单位为秒
  refresh-expire-time: 604800
  exclude-paths:
    - /api/v1/sysUser/login
    - /api/v1/sysUser/refresh
    - /api/v1/sysUser/captcha
    - /swagger/*
    - /jobs/script/
job:
  script:
    #  脚本执全局超时时间,0表示没有限制
    global-timeout: 60
    # 最大并发数
    max-concurrent: 10



